#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, in1,    potmobilelift,  sensorPotentiometer)
#pragma config(Sensor, in2,    potfourbar,     sensorPotentiometer)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, in4,    linetrackleft,  sensorLineFollower)
#pragma config(Sensor, in5,    linetrackright, sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightencoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  liftencoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  leftencoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           rightdrive1,   tmotorVex393HighSpeed_HBridge, openLoop, encoderPort, None)
#pragma config(Motor,  port2,           rightdrive2,   tmotorVex393HighSpeed_MC29, openLoop, encoderPort, None)
#pragma config(Motor,  port3,           fourbarleft,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           mobilelift,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           conelift,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           intake,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           fourbarright,  tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftdrive2,    tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port10,          leftdrive1,    tmotorVex393HighSpeed_HBridge, openLoop, reversed, encoderPort, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "SlewRateTask.c"


task mobilepickup()
{
	repeatUntil (SensorValue(potmobilelift)>=3750)
	{
		motor[mobilelift] = 127;
	}
	motor[mobilelift] = 0;
}

task mobileputdown()
{
	repeatUntil (SensorValue(potmobilelift)<=1390)
	{
		motor[mobilelift] = -127;
	}
	motor[mobilelift] = 0;
}



///////////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{

}

task usercontrol()
{

	startTask(MotorSlewRateTask);
	motorSlew[leftdrive1] = 20;
	motorSlew[rightdrive1] = 20;
	motorSlew[leftdrive2] = 20;
	motorSlew[rightdrive1] = 20;
	while (true)
	{
			if (vexRT[Btn7U]==1)
		{
			motor[fourbarleft] = 127;
			motor[fourbarright] = 127;
		}
		else if (vexRT[Btn7D]==1)
		{
			motor[fourbarleft] = -127;
			motor[fourbarright] = -127;
		}
		else
		{
			motor[fourbarleft] = 0;
			motor[fourbarright] = 0;
		}


			if (vexRT[Btn5U]==1)
		{
			motor[intake]=127;
		}

		else if (vexRT[Btn5D]==1)
		{
			motor[intake]=-127;
		}
		else
		{
			motor[intake]=15;
		}

					if (vexRT[Btn6U]==1)
		{
			motor[conelift]=127;
		}

		else if (vexRT[Btn6D]==1)
		{
			motor[conelift]=-127;
		}
		else
		{
			motor[conelift]=0;
		}

		motorReq[leftdrive1] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
		motorReq[leftdrive2] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
		motorReq[rightdrive2] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;
		motorReq[rightdrive1] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;




		if (vexRT[Btn8U]==1)
		{
			stopTask(mobileputdown);
			startTask(mobilepickup);
		}
		else if (vexRT[Btn8D]==1)
		{
			stopTask(mobilepickup);
			startTask(mobileputdown);
		}

	}
}
