#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    potconelift,    sensorPotentiometer)
#pragma config(Sensor, in2,    potchainbar,    sensorPotentiometer)
#pragma config(Sensor, in3,    potmobilelift,  sensorPotentiometer)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, in5,    linetracker,    sensorLineFollower)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftdrive1,    tmotorVex393HighSpeed_HBridge, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port2,           leftdrive2,    tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           conelift,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           mobilelift,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           chainbarleft,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           chainbarright, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           intake,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           rightdrive2,   tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port10,          rightdrive1,   tmotorVex393HighSpeed_HBridge, openLoop, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


///////////////////////////////////////////////////////////////////////////////////////////////


int auton = 0;


//ADD all autonomous choices
void displayAuton(){
	switch(auton){

	case 2:
		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);
		displayLCDCenteredString(0, "Programming");
		break;

	case 1:

		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);
		displayNextLCDNumber(SensorValue(I2C_1));
		displayNextLCDNumber(SensorValue(I2C_2));
		wait1Msec(100);



		break;


	case 0:
		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);
		displayLCDCenteredString(0, "20 point zone");
		break;




	case -1:

		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);
		displayLCDCenteredString(0, "5 point zone");
		break;


	case -2:

		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);
		displayLCDCenteredString(0, "Stationary Goal");
		break;

	case -3:

		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);
		displayLCDCenteredString(0, "None");
		break;

	default:
		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);
		string mainBattery, backupBattery;
		// Clear line 2 (1) of the LCD

		//Display the Primary Robot battery voltage
		displayLCDString(0, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
		displayNextLCDString(mainBattery);

		//Display the Backup battery voltage
		displayLCDString(1, 0, "Backup: ");
		sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');    //Build the value to be displayed
		displayNextLCDString(backupBattery);

		//Short delay for the LCD refresh rate
		wait1Msec(100);
		break;
	}
}


//DO NOT MODIFY
task LCDControl()
{
	clearLCDLine(0);
	clearLCDLine(1);
	bLCDBacklight = true;
	bool noButtonsPressed = true;
	displayAuton();
	while(true){
		if(noButtonsPressed){ // only update auton if a button is pressed AND wasn't pressed previously
			switch(nLCDButtons){
			case kButtonLeft:
				auton--;
				displayAuton();
				break;
			case kButtonCenter:
				stopTask(LCDControl);
				break;
			case kButtonRight:
				auton++;
				displayAuton();
				break;
			}
		}//if
		noButtonsPressed = !nLCDButtons; //update if there is a button currently pressed
		wait1Msec(20);
	}//while
}//task



void movedistance (int degrees, int power)
{
	SensorValue(I2C_1) = 0;
	SensorValue(I2C_2) = 0;
	repeatUntil(abs(SensorValue(I2C_1)) >= degrees)
	{
		motor[leftdrive1] = power;
		motor[leftdrive2]  = power;
		repeatUntil (abs(SensorValue(I2C_2)) >= degrees)
		{
			motor[rightdrive2] = power;
			motor[rightdrive1]  = power;
		}
	}

	SensorValue(I2C_1) = 0;
	SensorValue(I2C_2) = 0;
	if (power > 0)
	{
		motor[leftdrive1] = -10;
		motor[leftdrive2] = -10;
		motor[rightdrive2] = -10;
		motor[rightdrive1] =-10;
	}
	else
	{
		motor[leftdrive1] = 10;
		motor[leftdrive2] = 10;
		motor[rightdrive2] = 10;
		motor[rightdrive1] = 10;
	}
}

void movedistance1 (int degrees, int power)
{
	SensorValue(I2C_1) = 0;
	SensorValue(I2C_2) = 0;
	repeatUntil(abs(SensorValue(I2C_1)) >= degrees)
	{
		motor[leftdrive1] = power;
		motor[leftdrive2]  = power;
		repeatUntil (abs(SensorValue(I2C_2)) >= degrees)
		{
			motor[rightdrive2] = power;
			motor[rightdrive1]  = power;
		}
	}

	SensorValue(I2C_1) = 0;
	SensorValue(I2C_2) = 0;
	motor[leftdrive1] = 0;
	motor[leftdrive2] = 0;
	motor[rightdrive2] = 0;
	motor[rightdrive1] = 0;
}



task mobilepickup()
{

	repeatUntil (SensorValue(potmobilelift)>=3850)
	{
		motor[mobilelift] = 127;
	}
	motor[mobilelift] = 0;
}

task mobileputdown()
{
	repeatUntil (SensorValue(potmobilelift)<=1400)
	{
		motor[mobilelift] = -127;
	}
	motor[mobilelift] = 0;
}

////////////////////////////////////////////////////////////////////


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	resetMotorEncoder(leftdrive2);
	resetMotorEncoder(rightdrive2);
	SensorValue[gyro] = 0;

	bStopTasksBetweenModes = true;

	bDisplayCompetitionStatusOnLcd = false;

	startTask(LCDControl);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{

		//stopTask(LCDControl);
		//switch(auton){




/////////////////////////////////////////////////////Programming Skills///////////////////////////////////////////////////////


	//		repeatUntil(SensorValue(dgtl11)>= 20)
	//		{
	//			motor[conelift] = 127;
	//		}
	//		motor[conelift] = 0;

	//		startTask(mobileputdown);

	//		movedistance1(800,80);
	//		wait1Msec(500);
	//		startTask(mobilepickup);
	//		wait1Msec(1000);

	//		repeatUntil(SensorValue(in2) <=2700)
	//		{
	//			motor[leftdrive1] = -63;
	//			motor[leftdrive2] = -63;
	//			motor[rightdrive2] = -63;
	//			motor[rightdrive1] = -63;
	//		}

	//		motor[leftdrive1] = 0;
	//		motor[leftdrive2] = 0;
	//		motor[rightdrive2] = 0;
	//		motor[rightdrive1] = 0;

	//		wait1Msec(500);

	//		repeatUntil(SensorValue(in3) >= 800)
	//		{
	//			motor[leftdrive1] = -63;
	//			motor[leftdrive2] = -63;
	//			motor[rightdrive2] = 63;
	//			motor[rightdrive1] = 63;
	//		}

	//		motor[leftdrive1] = 10;
	//		motor[leftdrive2] = 10;
	//		motor[rightdrive2] = -10;
	//		motor[rightdrive1] = -10;

	//		wait1Msec(500);
	//		movedistance(400,63);

	//		wait1Msec(500);

	//		repeatUntil(SensorValue(in3) >= 1700)
	//		{
	//			motor[leftdrive1] = -63;
	//			motor[leftdrive2] = -63;
	//			motor[rightdrive2] = 63;
	//			motor[rightdrive1] = 63;
	//		}

	//		motor[leftdrive1] = 10;
	//		motor[leftdrive2] = 10;
	//		motor[rightdrive2] = -10;
	//		motor[rightdrive1] = -10;

	//		wait1Msec(500);

	//		movedistance1(450,127);

	//		startTask(mobileputdown);
	//		wait1Msec(1000);
	//		movedistance(50,-127);
	//		wait1Msec(200);

	//		startTask(mobilepickup);
	//		wait1Msec(1000);

	//		repeatUntil(SensorValue(in2) <=2700)
	//		{
	//			motor[leftdrive1] = -45;
	//			motor[leftdrive2] = -45;
	//			motor[rightdrive2] = -45;
	//			motor[rightdrive1] = -45;
	//		}

	//		motor[leftdrive1] = 0;
	//		motor[leftdrive2] = 0;
	//		motor[rightdrive2] = 0;
	//		motor[rightdrive1] = 0;

	//		wait1Msec(500);

	//		startTask(mobileputdown);

	//		repeatUntil(SensorValue(in3) <= 980)
	//		{
	//			motor[leftdrive1] = 63;
	//			motor[leftdrive2] = 63;
	//			motor[rightdrive2] = -63;
	//			motor[rightdrive1] = -63;
	//		}

	//		motor[leftdrive1] = -10;
	//		motor[leftdrive2] = -10;
	//		motor[rightdrive2] = 10;
	//		motor[rightdrive1] = 10;
	//		wait1Msec(500);
	//		movedistance(400,63);
	//		wait1Msec(500);

	//		repeatUntil(SensorValue(in3) <= 50)
	//		{
	//			motor[leftdrive1] = 63;
	//			motor[leftdrive2] = 63;
	//			motor[rightdrive2] = -63;
	//			motor[rightdrive1] = -63;
	//		}

	//		motor[leftdrive1] = -10;
	//		motor[leftdrive2] = -10;
	//		motor[rightdrive2] = 10;
	//		motor[rightdrive1] = 10;
	//		wait1Msec(500);

	//		movedistance1(300,80);
	//		wait1Msec(500);
	//		startTask(mobilepickup);
	//		wait1Msec(1000);

	//		repeatUntil(SensorValue(in3) >= 1710)
	//		{
	//			motor[leftdrive1] = -63;
	//			motor[leftdrive2] = -63;
	//			motor[rightdrive2] = 63;
	//			motor[rightdrive1] = 63;
	//		}

	//		motor[leftdrive1] = 10;
	//		motor[leftdrive2] = 10;
	//		motor[rightdrive2] = -10;
	//		motor[rightdrive1] = -10;

	//		wait1Msec(500);

	//		if (SensorValue(in3) < 1765)
	//		{
	//			repeatUntil(SensorValue(in3) >= 1765)
	//			{
	//				motor[leftdrive1] = -40;
	//				motor[leftdrive2] = -40;
	//				motor[rightdrive2] = 40;
	//				motor[rightdrive1] = 40;
	//			}
	//			motor[leftdrive1] = 10;
	//			motor[leftdrive2] = 10;
	//			motor[rightdrive2] = -10;
	//			motor[rightdrive1] = -10;
	//		}

	//		else if (SensorValue(in3) > 1765)
	//		{
	//			repeatUntil(SensorValue(in3) <=1765)
	//			{
	//				motor[leftdrive1] = 40;
	//				motor[leftdrive2] = 40;
	//				motor[rightdrive2] = -40;
	//				motor[rightdrive1] = -40;
	//			}
	//			motor[leftdrive1] = -10;
	//			motor[leftdrive2] = -10;
	//			motor[rightdrive2] = 10;
	//			motor[rightdrive1] = 10;
	//		}


	//		wait1Msec(500);



	//		repeatUntil(SensorValue(in2) <=2700)
	//		{
	//			motor[leftdrive1] = 50;
	//			motor[leftdrive2] = 50;
	//			motor[rightdrive2] = 50;
	//			motor[rightdrive1] = 50;
	//		}

	//		motor[leftdrive1] = 0;
	//		motor[leftdrive2] = 0;
	//		motor[rightdrive2] = 0;
	//		motor[rightdrive1] = 0;

	//		startTask(mobileputdown);
	//		wait1Msec(1000);



	//		movedistance(50,-63);
	//		startTask(mobilepickup);
	//		motor[leftdrive1] = 30;
	//		motor[leftdrive2] = 30;
	//		motor[rightdrive2] = 30;
	//		motor[rightdrive1] = 30;
	//		wait1Msec(500);

	//		SensorValue[in3] = 0;

	//		wait1Msec(500);

	//		movedistance(500,-63);
	//		wait1Msec(500);




	//		repeatUntil(SensorValue(in3) <= -1830)
	//		{
	//			motor[leftdrive1] = 50;
	//			motor[leftdrive2] = 50;
	//			motor[rightdrive2] = -50;
	//			motor[rightdrive1] = -50;
	//		}

	//		motor[leftdrive1] = -10;
	//		motor[leftdrive2] = -10;
	//		motor[rightdrive2] = 10;
	//		motor[rightdrive1] = 10;
	//		wait1Msec(500);

	//		if (SensorValue(in3) < -1860)
	//		{
	//			repeatUntil(SensorValue(in3) >= -1860)
	//			{
	//				motor[leftdrive1] = -40;
	//				motor[leftdrive2] = -40;
	//				motor[rightdrive2] = 40;
	//				motor[rightdrive1] = 40;
	//			}
	//			motor[leftdrive1] = 10;
	//			motor[leftdrive2] = 10;
	//			motor[rightdrive2] = -10;
	//			motor[rightdrive1] = -10;
	//		}

	//		else if (SensorValue(in3) > -1860)
	//		{
	//			repeatUntil(SensorValue(in3) <=1860)
	//			{
	//				motor[leftdrive1] = 40;
	//				motor[leftdrive2] = 40;
	//				motor[rightdrive2] = -40;
	//				motor[rightdrive1] = -40;
	//			}
	//			motor[leftdrive1] = -10;
	//			motor[leftdrive2] = -10;
	//			motor[rightdrive2] = 10;
	//			motor[rightdrive1] = 10;
	//		}


	//		wait1Msec(500);

	//		startTask(mobileputdown);
	//		wait1Msec(1000);

	//		movedistance1(1200,100);
	//		startTask(mobilepickup);
	//		wait1Msec(1000);

	//		movedistance(500,50);

	//		repeatUntil(SensorValue(in2) <=2700)
	//		{
	//			motor[leftdrive1] = 50;
	//			motor[leftdrive2] = 50;
	//			motor[rightdrive2] = 50;
	//			motor[rightdrive1] = 50;
	//		}

	//		motor[leftdrive1] = 0;
	//		motor[leftdrive2] = 0;
	//		motor[rightdrive2] = 0;
	//		motor[rightdrive1] = 0;

	//		startTask(mobileputdown);
	//		wait1Msec(1000);

	//		movedistance(50,-63);
	//		startTask(mobilepickup);
	//		motor[leftdrive1] = 30;
	//		motor[leftdrive2] = 30;
	//		motor[rightdrive2] = 30;
	//		motor[rightdrive1] = 30;
	//		wait1Msec(500);

	//		SensorValue[in3] = 0;

	//		wait1Msec(500);

	//		movedistance(50,-32);
	//		wait1Msec(500);

	//		repeatUntil(SensorValue(in3) <= -800)
	//		{
	//			motor[leftdrive1] = 63;
	//			motor[leftdrive2] = 63;
	//			motor[rightdrive2] = -63;
	//			motor[rightdrive1] = -63;
	//		}

	//		motor[leftdrive1] = -10;
	//		motor[leftdrive2] = -10;
	//		motor[rightdrive2] = 10;
	//		motor[rightdrive1] = 10;
	//		wait1Msec(500);

	//		movedistance(920,63);
	//		wait1Msec(500);

	//		startTask(mobileputdown);

	//		repeatUntil(SensorValue(in3) <= -1750)
	//		{
	//			motor[leftdrive1] = 63;
	//			motor[leftdrive2] = 63;
	//			motor[rightdrive2] = -63;
	//			motor[rightdrive1] = -63;
	//		}

	//		motor[leftdrive1] = -10;
	//		motor[leftdrive2] = -10;
	//		motor[rightdrive2] = 10;
	//		motor[rightdrive1] = 10;
	//		wait1Msec(500);

	//		movedistance1(600,80);
	//		wait1Msec(500);

	//		startTask(mobilepickup);
	//		wait1Msec(1000);

	//		repeatUntil(SensorValue(in2) <=2700)
	//		{
	//			motor[leftdrive1] = -63;
	//			motor[leftdrive2] = -63;
	//			motor[rightdrive2] = -63;
	//			motor[rightdrive1] = -63;
	//		}

	//		motor[leftdrive1] = 0;
	//		motor[leftdrive2] = 0;
	//		motor[rightdrive2] = 0;
	//		motor[rightdrive1] = 0;

	//		wait1Msec(500);

	//		SensorValue(in3) = 0;

	//		repeatUntil(SensorValue(in3) <= -860)
	//		{
	//			motor[leftdrive1] = 63;
	//			motor[leftdrive2] = 63;
	//			motor[rightdrive2] = -63;
	//			motor[rightdrive1] = -63;
	//		}

	//		motor[leftdrive1] = -10;
	//		motor[leftdrive2] = -10;
	//		motor[rightdrive2] = 10;
	//		motor[rightdrive1] = 10;
	//		wait1Msec(500);


	//		movedistance(350,63);

	//		wait1Msec(500);

	//		repeatUntil(SensorValue(in3) <= -1800)
	//		{
	//			motor[leftdrive1] = 63;
	//			motor[leftdrive2] = 63;
	//			motor[rightdrive2] = -63;
	//			motor[rightdrive1] = -63;
	//		}

	//		motor[leftdrive1] = -10;
	//		motor[leftdrive2] = -10;
	//		motor[rightdrive2] = 10;
	//		motor[rightdrive1] = 10;
	//		wait1Msec(500);

	//		movedistance(450,127);

	//		startTask(mobileputdown);
	//		wait1Msec(1000);
	//		movedistance(50,-127);
	//		wait1Msec(200);

	//		startTask(mobilepickup);
	//		wait1Msec(1000);

	//		repeatUntil(SensorValue(in2) <=2700)
	//		{
	//			motor[leftdrive1] = -55;
	//			motor[leftdrive2] = -55;
	//			motor[rightdrive2] = -55;
	//			motor[rightdrive1] = -55;
	//		}

	//		motor[leftdrive1] = 10;
	//		motor[leftdrive2] = 10;
	//		motor[rightdrive2] = 10;
	//		motor[rightdrive1] = 10;

	//		wait1Msec(500);

	//		repeatUntil(SensorValue(in3) >= -1400)
	//		{
	//			motor[leftdrive1] = -63;
	//			motor[leftdrive2] = -63;
	//			motor[rightdrive2] = 63;
	//			motor[rightdrive1] = 63;
	//		}

	//		motor[leftdrive1] = 10;
	//		motor[leftdrive2] = 10;
	//		motor[rightdrive2] = -10;
	//		motor[rightdrive1] = -10;
	//		wait1Msec(500);

	//		movedistance1(1600,-63);





/////////////////////////////////////////////////////Stationary Goal///////////////////////////////////////////////////////


	//repeatUntil(SensorValue(potchainbar) >= 850)
	//{
	//	motor[chainbarleft] = -50;
	//	motor[chainbarright] = -50;
	//}
	//	motor[chainbarleft] = 0;
	//	motor[chainbarright] = 0;

	//repeatUntil(SensorValue(potchainbar) <= 750)
	//{
	//	motor[chainbarleft] = 50;
	//	motor[chainbarright] = 50;
	//}
	//	motor[chainbarleft] = 0;
	//	motor[chainbarright] = 0;

	//repeatUntil(SensorValue(potconelift)>= 1700)
	//{
	//	motor[conelift] = 127;
	//}
	//motor[conelift] = 0;

	//repeatUntil(SensorValue(potchainbar) >= 3500)
	//{
	//	motor[chainbarleft] = -50;
	//	motor[chainbarright] = -50;
	//}
	//	motor[chainbarleft] = 0;
	//	motor[chainbarright] = 0;

	//movedistance(575,32);

	//wait1Msec(1000);

	//motor[intake] = -127;
	//wait1Msec(1000);
	//motor[intake] = 0;

	//movedistance(575,-32);




/////////////////////////////////////////////////////5 point zone right///////////////////////////////////////////////////////


//	repeatUntil(SensorValue(potchainbar) >= 850)
//	{
//		motor[chainbarleft] = -63;
//		motor[chainbarright] = -63;
//	}
//	motor[chainbarleft] = 0;
//	motor[chainbarright] = 0;

//	repeatUntil(SensorValue(potchainbar) <= 750)
//	{
//		motor[chainbarleft] = 63;
//		motor[chainbarright] = 63;
//	}
//	motor[chainbarleft] = 0;
//	motor[chainbarright] = 0;


//	startTask(mobileputdown);



//	repeatUntil(SensorValue(potconelift)>= 860)
//	{
//		motor[conelift] = 127;
//	}
//	motor[conelift] = 0;



//	movedistance(1000,100);

//	repeatUntil(SensorValue(in2) <=2700)
//	{
//		motor[leftdrive1] = 100;
//		motor[leftdrive2] = 100;
//		motor[rightdrive2] = 100;
//		motor[rightdrive1] =100;
//	}
//	motor[leftdrive1] = 0;
//	motor[leftdrive2] = 0;
//	motor[rightdrive2] = 0;
//	motor[rightdrive1] =0;

//	movedistance1(400,100);

//		startTask(mobilepickup);

//		repeatUntil(SensorValue(potconelift)>= 860)
//	{
//		motor[conelift] = 127;
//	}
//	motor[conelift] = 0;

//	wait1Msec(1500);

//	repeatUntil(SensorValue(potconelift)<= 620)
//	{
//		motor[conelift] = -127;
//	}
//	motor[conelift] = 0;

//	motor[intake] = -127;
//	wait1Msec(500);
//	motor[intake] = 0;

//	motor[intake] = 127;

//	movedistance(50,127);

//	repeatUntil(SensorValue(potchainbar) >= 3500)
//	{
//		motor[chainbarleft] = -127;
//		motor[chainbarright] = -127;
//	}
//	motor[chainbarleft] = 0;
//	motor[chainbarright] = 0;



//	repeatUntil(SensorValue(potchainbar) <= 750)
//	{
//		motor[chainbarleft] = 63;
//		motor[chainbarright] = 63;

//	}
//	motor[chainbarleft] = 0;
//	motor[chainbarright] = 0;


//	motor[intake] = 0;


//	motor[intake] = -127;
//	wait1Msec(500);
//	motor[intake] = 0;

//	movedistance(1250,-127);



//	wait1Msec(500);

//		repeatUntil(SensorValue(gyro) <=-1500)
//	{
//		motor[leftdrive1] = 127;
//		motor[leftdrive2] = 127;
//		motor[rightdrive2] = -127;
//		motor[rightdrive1] =-127;
//	}
//	motor[leftdrive1] = -10;
//	motor[leftdrive2] = -10;
//	motor[rightdrive2] = 10;
//	motor[rightdrive1] =10;

//	wait1Msec(500);


//	startTask(mobileputdown);

//					repeatUntil(SensorValue(potconelift)>= 860)
//	{
//		motor[conelift] = 127;

//	}
//	motor[conelift] = 0;

//wait1Msec(1500);

//movedistance1(200,-127);










/////////////////////////////////////////////////////5 point zone left///////////////////////////////////////////////////////


//	repeatUntil(SensorValue(potchainbar) >= 850)
//	{
//		motor[chainbarleft] = -63;
//		motor[chainbarright] = -63;
//	}
//	motor[chainbarleft] = 0;
//	motor[chainbarright] = 0;

//	repeatUntil(SensorValue(potchainbar) <= 750)
//	{
//		motor[chainbarleft] = 63;
//		motor[chainbarright] = 63;
//	}
//	motor[chainbarleft] = 0;
//	motor[chainbarright] = 0;


//	startTask(mobileputdown);



//	repeatUntil(SensorValue(potconelift)>= 860)
//	{
//		motor[conelift] = 127;
//	}
//	motor[conelift] = 0;



//	movedistance(1000,100);

//	repeatUntil(SensorValue(in2) <=2700)
//	{
//		motor[leftdrive1] = 100;
//		motor[leftdrive2] = 100;
//		motor[rightdrive2] = 100;
//		motor[rightdrive1] =100;
//	}
//	motor[leftdrive1] = 0;
//	motor[leftdrive2] = 0;
//	motor[rightdrive2] = 0;
//	motor[rightdrive1] =0;

//	movedistance1(400,100);

//		startTask(mobilepickup);

//		repeatUntil(SensorValue(potconelift)>= 860)
//	{
//		motor[conelift] = 127;
//	}
//	motor[conelift] = 0;

//	wait1Msec(1500);

//	repeatUntil(SensorValue(potconelift)<= 620)
//	{
//		motor[conelift] = -127;
//	}
//	motor[conelift] = 0;

//	motor[intake] = -127;
//	wait1Msec(500);
//	motor[intake] = 0;

//	motor[intake] = 127;

//	movedistance(50,127);

//	repeatUntil(SensorValue(potchainbar) >= 3500)
//	{
//		motor[chainbarleft] = -127;
//		motor[chainbarright] = -127;
//	}
//	motor[chainbarleft] = 0;
//	motor[chainbarright] = 0;



//	repeatUntil(SensorValue(potchainbar) <= 750)
//	{
//		motor[chainbarleft] = 63;
//		motor[chainbarright] = 63;

//	}
//	motor[chainbarleft] = 0;
//	motor[chainbarright] = 0;


//	motor[intake] = 0;


//	motor[intake] = -127;
//	wait1Msec(500);
//	motor[intake] = 0;

//	movedistance(1250,-127);



//	wait1Msec(500);

//		repeatUntil(SensorValue(gyro) >=1300)
//	{
//		motor[leftdrive1] = -127;
//		motor[leftdrive2] = -127;
//		motor[rightdrive2] = 127;
//		motor[rightdrive1] =127;
//	}
//	motor[leftdrive1] = 10;
//	motor[leftdrive2] = 10;
//	motor[rightdrive2] = -10;
//	motor[rightdrive1] =-10;

//	wait1Msec(500);


//	startTask(mobileputdown);

//					repeatUntil(SensorValue(potconelift)>= 860)
//	{
//		motor[conelift] = 127;

//	}
//	motor[conelift] = 0;

//wait1Msec(1500);

//movedistance1(200,-127);








///////////////////////////////////////////////////////20 point zone left///////////////////////////////////////////////////////


//	repeatUntil(SensorValue(potchainbar) >= 850)
//	{
//		motor[chainbarleft] = -63;
//		motor[chainbarright] = -63;
//	}
//	motor[chainbarleft] = 0;
//	motor[chainbarright] = 0;

//	repeatUntil(SensorValue(potchainbar) <= 750)
//	{
//		motor[chainbarleft] = 63;
//		motor[chainbarright] = 63;
//	}
//	motor[chainbarleft] = 0;
//	motor[chainbarright] = 0;


//	startTask(mobileputdown);



//	repeatUntil(SensorValue(potconelift)>= 860)
//	{
//		motor[conelift] = 127;
//	}
//	motor[conelift] = 0;



//	movedistance(1000,100);

//	repeatUntil(SensorValue(in2) <=2700)
//	{
//		motor[leftdrive1] = 100;
//		motor[leftdrive2] = 100;
//		motor[rightdrive2] = 100;
//		motor[rightdrive1] =100;
//	}
//	motor[leftdrive1] = 0;
//	motor[leftdrive2] = 0;
//	motor[rightdrive2] = 0;
//	motor[rightdrive1] =0;

//	movedistance1(400,100);

//		startTask(mobilepickup);

//		repeatUntil(SensorValue(potconelift)>= 860)
//	{
//		motor[conelift] = 127;
//	}
//	motor[conelift] = 0;

//	wait1Msec(1500);

//	repeatUntil(SensorValue(potconelift)<= 620)
//	{
//		motor[conelift] = -127;
//	}
//	motor[conelift] = 0;

//	motor[intake] = -127;
//	wait1Msec(500);
//	motor[intake] = 0;

//	motor[intake] = 127;

//	movedistance(50,127);

//	repeatUntil(SensorValue(potchainbar) >= 3500)
//	{
//		motor[chainbarleft] = -127;
//		motor[chainbarright] = -127;
//	}
//	motor[chainbarleft] = 0;
//	motor[chainbarright] = 0;



//	repeatUntil(SensorValue(potchainbar) <= 750)
//	{
//		motor[chainbarleft] = 63;
//		motor[chainbarright] = 63;

//		repeatUntil(SensorValue(in2) <=2700)
//	{
//		motor[leftdrive1] = -127;
//		motor[leftdrive2] = -127;
//		motor[rightdrive2] = -127;
//		motor[rightdrive1] =-127;
//	}
//	motor[leftdrive1] = 0;
//	motor[leftdrive2] = 0;
//	motor[rightdrive2] = 0;
//	motor[rightdrive1] =0;

//	movedistance(50,-127);

//	}
//	motor[chainbarleft] = 0;
//	motor[chainbarright] = 0;

//motor[intake] = 0;


//	motor[intake] = -127;
//	wait1Msec(500);
//	motor[intake] = 0;

//	wait1Msec(500);

//		repeatUntil(SensorValue(gyro) >=230)
//	{
//		motor[leftdrive1] = -127;
//		motor[leftdrive2] = -127;
//		motor[rightdrive2] = 127;
//		motor[rightdrive1] =127;
//	}
//	motor[leftdrive1] = 10;
//	motor[leftdrive2] = 10;
//	motor[rightdrive2] = -10;
//	motor[rightdrive1] =-10;

//	wait1Msec(500);

//	movedistance(700,-127);

//	wait1Msec(500);

//			repeatUntil(SensorValue(gyro) >=1120)
//	{
//		motor[leftdrive1] = -127;
//		motor[leftdrive2] = -127;
//		motor[rightdrive2] = 127;
//		motor[rightdrive1] =127;
//	}
//	motor[leftdrive1] = 10;
//	motor[leftdrive2] = 10;
//	motor[rightdrive2] = -10;
//	motor[rightdrive1] =-10;

//	wait1Msec(500);




//			movedistance1(550,127);
//	startTask(mobileputdown);

//					repeatUntil(SensorValue(potconelift)>= 860)
//	{
//		motor[conelift] = 127;

//	}
//	motor[conelift] = 0;

//wait1Msec(1500);

//movedistance1(200,-127);








///////////////////////////////////////////////////////////////20 point zone right///////////////////////////////////////////
//	repeatUntil(SensorValue(potchainbar) >= 850)
//	{
//		motor[chainbarleft] = -63;
//		motor[chainbarright] = -63;
//	}
//	motor[chainbarleft] = 0;
//	motor[chainbarright] = 0;

//	repeatUntil(SensorValue(potchainbar) <= 750)
//	{
//		motor[chainbarleft] = 63;
//		motor[chainbarright] = 63;
//	}
//	motor[chainbarleft] = 0;
//	motor[chainbarright] = 0;


//	startTask(mobileputdown);



//	repeatUntil(SensorValue(potconelift)>= 860)
//	{
//		motor[conelift] = 127;
//	}
//	motor[conelift] = 0;



//	movedistance(1000,100);

//	repeatUntil(SensorValue(in2) <=2700)
//	{
//		motor[leftdrive1] = 100;
//		motor[leftdrive2] = 100;
//		motor[rightdrive2] = 100;
//		motor[rightdrive1] =100;
//	}
//	motor[leftdrive1] = 0;
//	motor[leftdrive2] = 0;
//	motor[rightdrive2] = 0;
//	motor[rightdrive1] =0;

//	movedistance1(400,100);

//		startTask(mobilepickup);

//		repeatUntil(SensorValue(potconelift)>= 860)
//	{
//		motor[conelift] = 127;
//	}
//	motor[conelift] = 0;

//	wait1Msec(1500);

//	repeatUntil(SensorValue(potconelift)<= 620)
//	{
//		motor[conelift] = -127;
//	}
//	motor[conelift] = 0;

//	motor[intake] = -127;
//	wait1Msec(500);
//	motor[intake] = 0;

//	motor[intake] = 127;

//	movedistance(50,127);

//	repeatUntil(SensorValue(potchainbar) >= 3500)
//	{
//		motor[chainbarleft] = -127;
//		motor[chainbarright] = -127;
//	}
//	motor[chainbarleft] = 0;
//	motor[chainbarright] = 0;



//	repeatUntil(SensorValue(potchainbar) <= 750)
//	{
//		motor[chainbarleft] = 63;
//		motor[chainbarright] = 63;

//		repeatUntil(SensorValue(in2) <=2700)
//	{
//		motor[leftdrive1] = -127;
//		motor[leftdrive2] = -127;
//		motor[rightdrive2] = -127;
//		motor[rightdrive1] =-127;
//	}
//	motor[leftdrive1] = 0;
//	motor[leftdrive2] = 0;
//	motor[rightdrive2] = 0;
//	motor[rightdrive1] =0;

//	movedistance(50,-127);

//	}
//	motor[chainbarleft] = 0;
//	motor[chainbarright] = 0;

//motor[intake] = 0;


//	motor[intake] = -127;
//	wait1Msec(500);
//	motor[intake] = 0;

//	wait1Msec(500);

//		repeatUntil(SensorValue(gyro) <=-375)
//	{
//		motor[leftdrive1] = 127;
//		motor[leftdrive2] = 127;
//		motor[rightdrive2] = -127;
//		motor[rightdrive1] =-127;
//	}
//	motor[leftdrive1] = -10;
//	motor[leftdrive2] = -10;
//	motor[rightdrive2] = 10;
//	motor[rightdrive1] =10;

//	wait1Msec(500);

//	movedistance(800,-127);

//	wait1Msec(500);

//			repeatUntil(SensorValue(gyro) <=-1350)
//	{
//		motor[leftdrive1] = 127;
//		motor[leftdrive2] = 127;
//		motor[rightdrive2] = -127;
//		motor[rightdrive1] =-127;
//	}
//	motor[leftdrive1] = -10;
//	motor[leftdrive2] = -10;
//	motor[rightdrive2] = 10;
//	motor[rightdrive1] =10;

//	wait1Msec(500);




//			movedistance1(500,127);
//	startTask(mobileputdown);

//					repeatUntil(SensorValue(potconelift)>= 860)
//	{
//		motor[conelift] = 127;

//	}
//	motor[conelift] = 0;

//wait1Msec(1500);

//movedistance1(200,-127);





	/////////////////////////////////////////////////////////////////////////////////////



	//	case 2:// programming skills


	//		repeatUntil(SensorValue(dgtl11)>= 20)
	//		{
	//			motor[conelift] = 127;
	//		}
	//		motor[conelift] = 0;

	//		startTask(mobileputdown);

	//		movedistance1(800,80);
	//		wait1Msec(500);
	//		startTask(mobilepickup);
	//		wait1Msec(1000);

	//		repeatUntil(SensorValue(in2) <=2700)
	//		{
	//			motor[leftdrive1] = -63;
	//			motor[leftdrive2] = -63;
	//			motor[rightdrive2] = -63;
	//			motor[rightdrive1] = -63;
	//		}

	//		motor[leftdrive1] = 0;
	//		motor[leftdrive2] = 0;
	//		motor[rightdrive2] = 0;
	//		motor[rightdrive1] = 0;

	//		wait1Msec(500);

	//		repeatUntil(SensorValue(in3) >= 800)
	//		{
	//			motor[leftdrive1] = -63;
	//			motor[leftdrive2] = -63;
	//			motor[rightdrive2] = 63;
	//			motor[rightdrive1] = 63;
	//		}

	//		motor[leftdrive1] = 10;
	//		motor[leftdrive2] = 10;
	//		motor[rightdrive2] = -10;
	//		motor[rightdrive1] = -10;

	//		wait1Msec(500);
	//		movedistance(400,63);

	//		wait1Msec(500);

	//		repeatUntil(SensorValue(in3) >= 1700)
	//		{
	//			motor[leftdrive1] = -63;
	//			motor[leftdrive2] = -63;
	//			motor[rightdrive2] = 63;
	//			motor[rightdrive1] = 63;
	//		}

	//		motor[leftdrive1] = 10;
	//		motor[leftdrive2] = 10;
	//		motor[rightdrive2] = -10;
	//		motor[rightdrive1] = -10;

	//		wait1Msec(500);

	//		movedistance1(450,127);

	//		startTask(mobileputdown);
	//		wait1Msec(1000);
	//		movedistance(50,-127);
	//		wait1Msec(200);

	//		startTask(mobilepickup);
	//		wait1Msec(1000);

	//		repeatUntil(SensorValue(in2) <=2700)
	//		{
	//			motor[leftdrive1] = -45;
	//			motor[leftdrive2] = -45;
	//			motor[rightdrive2] = -45;
	//			motor[rightdrive1] = -45;
	//		}

	//		motor[leftdrive1] = 0;
	//		motor[leftdrive2] = 0;
	//		motor[rightdrive2] = 0;
	//		motor[rightdrive1] = 0;

	//		wait1Msec(500);

	//		startTask(mobileputdown);

	//		repeatUntil(SensorValue(in3) <= 980)
	//		{
	//			motor[leftdrive1] = 63;
	//			motor[leftdrive2] = 63;
	//			motor[rightdrive2] = -63;
	//			motor[rightdrive1] = -63;
	//		}

	//		motor[leftdrive1] = -10;
	//		motor[leftdrive2] = -10;
	//		motor[rightdrive2] = 10;
	//		motor[rightdrive1] = 10;
	//		wait1Msec(500);
	//		movedistance(400,63);
	//		wait1Msec(500);

	//		repeatUntil(SensorValue(in3) <= 50)
	//		{
	//			motor[leftdrive1] = 63;
	//			motor[leftdrive2] = 63;
	//			motor[rightdrive2] = -63;
	//			motor[rightdrive1] = -63;
	//		}

	//		motor[leftdrive1] = -10;
	//		motor[leftdrive2] = -10;
	//		motor[rightdrive2] = 10;
	//		motor[rightdrive1] = 10;
	//		wait1Msec(500);

	//		movedistance1(300,80);
	//		wait1Msec(500);
	//		startTask(mobilepickup);
	//		wait1Msec(1000);

	//		repeatUntil(SensorValue(in3) >= 1710)
	//		{
	//			motor[leftdrive1] = -63;
	//			motor[leftdrive2] = -63;
	//			motor[rightdrive2] = 63;
	//			motor[rightdrive1] = 63;
	//		}

	//		motor[leftdrive1] = 10;
	//		motor[leftdrive2] = 10;
	//		motor[rightdrive2] = -10;
	//		motor[rightdrive1] = -10;

	//		wait1Msec(500);

	//		if (SensorValue(in3) < 1765)
	//		{
	//			repeatUntil(SensorValue(in3) >= 1765)
	//			{
	//				motor[leftdrive1] = -40;
	//				motor[leftdrive2] = -40;
	//				motor[rightdrive2] = 40;
	//				motor[rightdrive1] = 40;
	//			}
	//			motor[leftdrive1] = 10;
	//			motor[leftdrive2] = 10;
	//			motor[rightdrive2] = -10;
	//			motor[rightdrive1] = -10;
	//		}

	//		else if (SensorValue(in3) > 1765)
	//		{
	//			repeatUntil(SensorValue(in3) <=1765)
	//			{
	//				motor[leftdrive1] = 40;
	//				motor[leftdrive2] = 40;
	//				motor[rightdrive2] = -40;
	//				motor[rightdrive1] = -40;
	//			}
	//			motor[leftdrive1] = -10;
	//			motor[leftdrive2] = -10;
	//			motor[rightdrive2] = 10;
	//			motor[rightdrive1] = 10;
	//		}


	//		wait1Msec(500);



	//		repeatUntil(SensorValue(in2) <=2700)
	//		{
	//			motor[leftdrive1] = 50;
	//			motor[leftdrive2] = 50;
	//			motor[rightdrive2] = 50;
	//			motor[rightdrive1] = 50;
	//		}

	//		motor[leftdrive1] = 0;
	//		motor[leftdrive2] = 0;
	//		motor[rightdrive2] = 0;
	//		motor[rightdrive1] = 0;

	//		startTask(mobileputdown);
	//		wait1Msec(1000);



	//		movedistance(50,-63);
	//		startTask(mobilepickup);
	//		motor[leftdrive1] = 30;
	//		motor[leftdrive2] = 30;
	//		motor[rightdrive2] = 30;
	//		motor[rightdrive1] = 30;
	//		wait1Msec(500);

	//		SensorValue[in3] = 0;

	//		wait1Msec(500);

	//		movedistance(500,-63);
	//		wait1Msec(500);




	//		repeatUntil(SensorValue(in3) <= -1830)
	//		{
	//			motor[leftdrive1] = 50;
	//			motor[leftdrive2] = 50;
	//			motor[rightdrive2] = -50;
	//			motor[rightdrive1] = -50;
	//		}

	//		motor[leftdrive1] = -10;
	//		motor[leftdrive2] = -10;
	//		motor[rightdrive2] = 10;
	//		motor[rightdrive1] = 10;
	//		wait1Msec(500);

	//		if (SensorValue(in3) < -1860)
	//		{
	//			repeatUntil(SensorValue(in3) >= -1860)
	//			{
	//				motor[leftdrive1] = -40;
	//				motor[leftdrive2] = -40;
	//				motor[rightdrive2] = 40;
	//				motor[rightdrive1] = 40;
	//			}
	//			motor[leftdrive1] = 10;
	//			motor[leftdrive2] = 10;
	//			motor[rightdrive2] = -10;
	//			motor[rightdrive1] = -10;
	//		}

	//		else if (SensorValue(in3) > -1860)
	//		{
	//			repeatUntil(SensorValue(in3) <=1860)
	//			{
	//				motor[leftdrive1] = 40;
	//				motor[leftdrive2] = 40;
	//				motor[rightdrive2] = -40;
	//				motor[rightdrive1] = -40;
	//			}
	//			motor[leftdrive1] = -10;
	//			motor[leftdrive2] = -10;
	//			motor[rightdrive2] = 10;
	//			motor[rightdrive1] = 10;
	//		}


	//		wait1Msec(500);

	//		startTask(mobileputdown);
	//		wait1Msec(1000);

	//		movedistance1(1200,100);
	//		startTask(mobilepickup);
	//		wait1Msec(1000);

	//		movedistance(500,50);

	//		repeatUntil(SensorValue(in2) <=2700)
	//		{
	//			motor[leftdrive1] = 50;
	//			motor[leftdrive2] = 50;
	//			motor[rightdrive2] = 50;
	//			motor[rightdrive1] = 50;
	//		}

	//		motor[leftdrive1] = 0;
	//		motor[leftdrive2] = 0;
	//		motor[rightdrive2] = 0;
	//		motor[rightdrive1] = 0;

	//		startTask(mobileputdown);
	//		wait1Msec(1000);

	//		movedistance(50,-63);
	//		startTask(mobilepickup);
	//		motor[leftdrive1] = 30;
	//		motor[leftdrive2] = 30;
	//		motor[rightdrive2] = 30;
	//		motor[rightdrive1] = 30;
	//		wait1Msec(500);

	//		SensorValue[in3] = 0;

	//		wait1Msec(500);

	//		movedistance(50,-32);
	//		wait1Msec(500);

	//		repeatUntil(SensorValue(in3) <= -800)
	//		{
	//			motor[leftdrive1] = 63;
	//			motor[leftdrive2] = 63;
	//			motor[rightdrive2] = -63;
	//			motor[rightdrive1] = -63;
	//		}

	//		motor[leftdrive1] = -10;
	//		motor[leftdrive2] = -10;
	//		motor[rightdrive2] = 10;
	//		motor[rightdrive1] = 10;
	//		wait1Msec(500);

	//		movedistance(920,63);
	//		wait1Msec(500);

	//		startTask(mobileputdown);

	//		repeatUntil(SensorValue(in3) <= -1750)
	//		{
	//			motor[leftdrive1] = 63;
	//			motor[leftdrive2] = 63;
	//			motor[rightdrive2] = -63;
	//			motor[rightdrive1] = -63;
	//		}

	//		motor[leftdrive1] = -10;
	//		motor[leftdrive2] = -10;
	//		motor[rightdrive2] = 10;
	//		motor[rightdrive1] = 10;
	//		wait1Msec(500);

	//		movedistance1(600,80);
	//		wait1Msec(500);

	//		startTask(mobilepickup);
	//		wait1Msec(1000);

	//		repeatUntil(SensorValue(in2) <=2700)
	//		{
	//			motor[leftdrive1] = -63;
	//			motor[leftdrive2] = -63;
	//			motor[rightdrive2] = -63;
	//			motor[rightdrive1] = -63;
	//		}

	//		motor[leftdrive1] = 0;
	//		motor[leftdrive2] = 0;
	//		motor[rightdrive2] = 0;
	//		motor[rightdrive1] = 0;

	//		wait1Msec(500);

	//		SensorValue(in3) = 0;

	//		repeatUntil(SensorValue(in3) <= -860)
	//		{
	//			motor[leftdrive1] = 63;
	//			motor[leftdrive2] = 63;
	//			motor[rightdrive2] = -63;
	//			motor[rightdrive1] = -63;
	//		}

	//		motor[leftdrive1] = -10;
	//		motor[leftdrive2] = -10;
	//		motor[rightdrive2] = 10;
	//		motor[rightdrive1] = 10;
	//		wait1Msec(500);


	//		movedistance(350,63);

	//		wait1Msec(500);

	//		repeatUntil(SensorValue(in3) <= -1800)
	//		{
	//			motor[leftdrive1] = 63;
	//			motor[leftdrive2] = 63;
	//			motor[rightdrive2] = -63;
	//			motor[rightdrive1] = -63;
	//		}

	//		motor[leftdrive1] = -10;
	//		motor[leftdrive2] = -10;
	//		motor[rightdrive2] = 10;
	//		motor[rightdrive1] = 10;
	//		wait1Msec(500);

	//		movedistance(450,127);

	//		startTask(mobileputdown);
	//		wait1Msec(1000);
	//		movedistance(50,-127);
	//		wait1Msec(200);

	//		startTask(mobilepickup);
	//		wait1Msec(1000);

	//		repeatUntil(SensorValue(in2) <=2700)
	//		{
	//			motor[leftdrive1] = -55;
	//			motor[leftdrive2] = -55;
	//			motor[rightdrive2] = -55;
	//			motor[rightdrive1] = -55;
	//		}

	//		motor[leftdrive1] = 10;
	//		motor[leftdrive2] = 10;
	//		motor[rightdrive2] = 10;
	//		motor[rightdrive1] = 10;

	//		wait1Msec(500);

	//		repeatUntil(SensorValue(in3) >= -1400)
	//		{
	//			motor[leftdrive1] = -63;
	//			motor[leftdrive2] = -63;
	//			motor[rightdrive2] = 63;
	//			motor[rightdrive1] = 63;
	//		}

	//		motor[leftdrive1] = 10;
	//		motor[leftdrive2] = 10;
	//		motor[rightdrive2] = -10;
	//		motor[rightdrive1] = -10;
	//		wait1Msec(500);

	//		movedistance1(1600,-63);

	//		break;

	//	case -3:




	//		break;




	//	case -2: // stationary goal

	//repeatUntil(SensorValue(potchainbar) >= 850)
	//{
	//	motor[chainbarleft] = -50;
	//	motor[chainbarright] = -50;
	//}
	//	motor[chainbarleft] = 0;
	//	motor[chainbarright] = 0;

	//repeatUntil(SensorValue(potchainbar) <= 750)
	//{
	//	motor[chainbarleft] = 50;
	//	motor[chainbarright] = 50;
	//}
	//	motor[chainbarleft] = 0;
	//	motor[chainbarright] = 0;

	//repeatUntil(SensorValue(potconelift)>= 1700)
	//{
	//	motor[conelift] = 127;
	//}
	//motor[conelift] = 0;

	//repeatUntil(SensorValue(potchainbar) >= 3500)
	//{
	//	motor[chainbarleft] = -50;
	//	motor[chainbarright] = -50;
	//}
	//	motor[chainbarleft] = 0;
	//	motor[chainbarright] = 0;

	//movedistance(565,32);

	//wait1Msec(1000);

	//motor[intake] = -127;
	//wait1Msec(1000);
	//motor[intake] = 0;

	//movedistance(565,-32);
	//		break;

	//	case -1: // 5 point zone

	//		repeatUntil(SensorValue(dgtl1) <= -350)
	//		{
	//			motor[chainbar] = -127;
	//		}
	//		motor[chainbar] = 0;

	//		repeatUntil(SensorValue(dgtl1) >= -310)
	//		{
	//			motor[chainbar] = 127;
	//		}
	//		motor[chainbar] = 0;



	//		repeatUntil(SensorValue(dgtl11)>= 20)
	//		{
	//			motor[conelift] = 127;
	//		}
	//		motor[conelift] = 20;

	//		startTask(mobileputdown);



	//		movedistance(1000,127);

	//		repeatUntil(SensorValue(in2) <=2700)
	//		{
	//			motor[leftdrive1] = 127;
	//			motor[leftdrive2] = 127;
	//			motor[rightdrive2] = 127;
	//			motor[rightdrive1] =127;
	//		}
	//		motor[leftdrive1] = 0;
	//		motor[leftdrive2] = 0;
	//		motor[rightdrive2] = 0;
	//		motor[rightdrive1] =0;

	//		wait1Msec(500);

	//		startTask(mobilepickup);
	//		wait1Msec(1000);

	//		repeatUntil(SensorValue(dgtl11)<= 5)
	//		{
	//			motor[conelift] = -127;
	//		}
	//		motor[conelift] = 0;

	//		motor[intake] = -127;
	//		wait1Msec(800);
	//		motor[intake] = 0;


	//		repeatUntil(SensorValue(dgtl11)>= 20)
	//		{
	//			motor[conelift] = 127;
	//		}
	//		motor[conelift] = 0;



	//		movedistance(900,-127);

	//		wait1Msec(500);

	//		repeatUntil (SensorValue(in3) >= 1300)
	//		{
	//			motor[leftdrive1] = -100;
	//			motor[leftdrive2] = -100;
	//			motor[rightdrive2] = 100;
	//			motor[rightdrive1] = 100;
	//		}

	//		motor[leftdrive1] = 10;
	//		motor[leftdrive2] = 10;
	//		motor[rightdrive2] = -10;
	//		motor[rightdrive1] = -10;

	//		wait1Msec(500);
	//		startTask(mobileputdown);
	//		wait1Msec(1000);
	//		movedistance1(200,-127);

	//		break;


	//	case 0: // 20 point zone



	//		repeatUntil(SensorValue(dgtl1) <= -350)
	//		{
	//			motor[chainbar] = -127;
	//		}
	//		motor[chainbar] = 0;

	//		repeatUntil(SensorValue(dgtl1) >= -310)
	//		{
	//			motor[chainbar] = 127;
	//		}
	//		motor[chainbar] = 0;



	//		repeatUntil(SensorValue(dgtl11)>= 20)
	//		{
	//			motor[conelift] = 127;
	//		}
	//		motor[conelift] = 20;

	//		startTask(mobileputdown);



	//		movedistance(1000,127);

	//		repeatUntil(SensorValue(in2) <=2700)
	//		{
	//			motor[leftdrive1] = 127;
	//			motor[leftdrive2] = 127;
	//			motor[rightdrive2] = 127;
	//			motor[rightdrive1] =127;
	//		}
	//		motor[leftdrive1] = 0;
	//		motor[leftdrive2] = 0;
	//		motor[rightdrive2] = 0;
	//		motor[rightdrive1] =0;

	//		wait1Msec(500);

	//		startTask(mobilepickup);
	//		wait1Msec(1000);

	//		repeatUntil(SensorValue(dgtl11)<= 5)
	//		{
	//			motor[conelift] = -127;
	//		}
	//		motor[conelift] = 0;

	//		motor[intake] = -127;
	//		wait1Msec(800);
	//		motor[intake] = 0;


	//		repeatUntil(SensorValue(dgtl11)>= 20)
	//		{
	//			motor[conelift] = 127;
	//		}
	//		motor[conelift] = 0;


	//		movedistance(1000,-127);

	//		repeatUntil(SensorValue(in2) <=2700)
	//		{
	//			motor[leftdrive1] = -127;
	//			motor[leftdrive2] = -127;
	//			motor[rightdrive2] = -127;
	//			motor[rightdrive1] =-127;
	//		}
	//		motor[leftdrive1] = 0;
	//		motor[leftdrive2] = 0;
	//		motor[rightdrive2] = 0;
	//		motor[rightdrive1] =0;

	//		wait1Msec(1000);

	//		repeatUntil(SensorValue(in3) <= -420)
	//		{
	//			motor[leftdrive1] = 63;
	//			motor[leftdrive2] = 63;
	//			motor[rightdrive2] = -63;
	//			motor[rightdrive1] = -63;
	//		}

	//		motor[leftdrive1] = -10;
	//		motor[leftdrive2] = -10;
	//		motor[rightdrive2] = 10;
	//		motor[rightdrive1] = 10;

	//		wait1Msec(500);
	//		movedistance(500,-127);

	//		wait1Msec(500);


	//		repeatUntil(SensorValue(in3) <= -1425)
	//		{
	//			motor[leftdrive1] = 63;
	//			motor[leftdrive2] = 63;
	//			motor[rightdrive2] = -63;
	//			motor[rightdrive1] = -63;
	//		}

	//		motor[leftdrive1] = -10;
	//		motor[leftdrive2] = -10;
	//		motor[rightdrive2] = 10;
	//		motor[rightdrive1] = 10;


	//		wait1Msec(500);
	//		movedistance1(500,127);
	//		wait1Msec(100);

	//		startTask(mobileputdown);
	//		wait1Msec(1000);

	//		movedistance(50,-127);
	//		startTask(mobilepickup);
	//		break;

	//	case 1: // I2C Checker

	//		break;

	//	default: // battery displayer

	//		break;
	//	}

}


task usercontrol()
{
	stopTask(LCDControl);

	while (true)
	{

		motor[leftdrive1] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
		motor[leftdrive2] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
		motor[rightdrive2] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;
		motor[rightdrive1] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;


		if (vexRT[Btn6D]==1)
		{
			stopTask(mobilepickup);
			startTask(mobileputdown);
		}

		if (vexRT[Btn6U]==1)
		{
			stopTask(mobileputdown);
			startTask(mobilepickup);

		}



		if (vexRT[Btn5UXmtr2]==1)
		{
			motor[intake]=127;
		}

		else if (vexRT[Btn5DXmtr2]==1)
		{
			motor[intake]=-127;
		}
		else
		{
			motor[intake]=0;
		}


		if (vexRT[Btn7UXmtr2]==1)
		{
			motor[chainbarleft] = 127;
			motor[chainbarright] = 127;
		}
		else if (vexRT[Btn7DXmtr2]==1)
		{
			motor[chainbarleft] = -127;
			motor[chainbarright] = -127;
		}
		else
		{
			motor[chainbarleft] = 0;
			motor[chainbarright] = 0;
		}


		if (vexRT[Btn6UXmtr2]==1)
		{
			motor[conelift] = 127;
		}
		else if (vexRT[Btn6DXmtr2]==1)
		{
			motor[conelift] = -127;
		}

		else
		{
			motor[conelift] = 0;
		}




	}
}
