#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    potconelift,    sensorPotentiometer)
#pragma config(Sensor, in2,    potchainbar,    sensorPotentiometer)
#pragma config(Sensor, in3,    potmobilelift,  sensorPotentiometer)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, in5,    linetracker,    sensorLineFollower)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftdrive1,    tmotorVex393HighSpeed_HBridge, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port2,           leftdrive2,    tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           conelift,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           mobilelift,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           chainbarleft,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           chainbarright, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightdrive2,   tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port10,          rightdrive1,   tmotorVex393HighSpeed_HBridge, openLoop, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


///////////////////////////////////////////////////////////////////////////////////////////////


int auton = 0;
void displayAuton(){
	switch(auton){

	case 2:
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDCenteredString(0, "Programming");
		break;

	case 1:
		clearLCDLine(0);
		clearLCDLine(1);
		displayNextLCDNumber(SensorValue(I2C_1));
		displayNextLCDNumber(SensorValue(I2C_2));
		wait1Msec(100);
		break;

	case 0:
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDCenteredString(0, "20 point zone");
		break;

	case -1:

		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDCenteredString(0, "5 point zone");
		break;


	case -2:

		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDCenteredString(0, "Stationary Goal");
		break;

	case -3:

		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);
		displayLCDCenteredString(0, "None");
		break;

	default:
		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);
		string mainBattery, backupBattery;
		// Clear line 2 (1) of the LCD

		//Display the Primary Robot battery voltage
		displayLCDString(0, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
		displayNextLCDString(mainBattery);

		//Display the Backup battery voltage
		displayLCDString(1, 0, "Backup: ");
		sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');    //Build the value to be displayed
		displayNextLCDString(backupBattery);

		//Short delay for the LCD refresh rate
		wait1Msec(100);
		break;
	}
}


//DO NOT MODIFY
task LCDControl()
{
	clearLCDLine(0);
	clearLCDLine(1);
	bLCDBacklight = true;
	bool noButtonsPressed = true;
	displayAuton();
	while(true){
		if(noButtonsPressed){ // only update auton if a button is pressed AND wasn't pressed previously
			switch(nLCDButtons){
			case kButtonLeft:
				auton--;
				displayAuton();
				break;
			case kButtonCenter:
				stopTask(LCDControl);
				break;
			case kButtonRight:
				auton++;
				displayAuton();
				break;
			}
		}//if
		noButtonsPressed = !nLCDButtons; //update if there is a button currently pressed
		wait1Msec(20);
	}//while
}//task



void movedistance (int degrees, int power)
{
	SensorValue(I2C_1) = 0;
	SensorValue(I2C_2) = 0;
	repeatUntil(abs(SensorValue(I2C_1)) >= degrees)
	{
		motor[leftdrive1] = power;
		motor[leftdrive2]  = power;
		repeatUntil (abs(SensorValue(I2C_2)) >= degrees)
		{
			motor[rightdrive2] = power;
			motor[rightdrive1]  = power;
		}
	}

	SensorValue(I2C_1) = 0;
	SensorValue(I2C_2) = 0;
	if (power > 0)
	{
		motor[leftdrive1] = -10;
		motor[leftdrive2] = -10;
		motor[rightdrive2] = -10;
		motor[rightdrive1] =-10;
	}
	else
	{
		motor[leftdrive1] = 10;
		motor[leftdrive2] = 10;
		motor[rightdrive2] = 10;
		motor[rightdrive1] = 10;
	}
}

void movedistance1 (int degrees, int power)
{
	SensorValue(I2C_1) = 0;
	SensorValue(I2C_2) = 0;
	repeatUntil(abs(SensorValue(I2C_1)) >= degrees)
	{
		motor[leftdrive1] = power;
		motor[leftdrive2]  = power;
		repeatUntil (abs(SensorValue(I2C_2)) >= degrees)
		{
			motor[rightdrive2] = power;
			motor[rightdrive1]  = power;
		}
	}

	SensorValue(I2C_1) = 0;
	SensorValue(I2C_2) = 0;
	motor[leftdrive1] = 0;
	motor[leftdrive2] = 0;
	motor[rightdrive2] = 0;
	motor[rightdrive1] = 0;
}



task mobilepickup()
{
	repeatUntil (SensorValue(potmobilelift)<=350)
	{
		motor[mobilelift] = 127;
	}
	motor[mobilelift] = 0;
}

task mobileputdown()
{
	repeatUntil (SensorValue(potmobilelift)>=2410)
	{
		motor[mobilelift] = -127;
	}
	motor[mobilelift] = 0;
}\

////////////////////////////////////////////////////////////////////


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	resetMotorEncoder(leftdrive2);
	resetMotorEncoder(rightdrive2);

	bStopTasksBetweenModes = true;

	bDisplayCompetitionStatusOnLcd = false;

	startTask(LCDControl);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{

}

task usercontrol()
{
	stopTask(LCDControl);

	while (true)
	{

		motor[leftdrive1] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
		motor[leftdrive2] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
		motor[rightdrive2] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;
		motor[rightdrive1] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;


		if (vexRT[Btn5U]==1)
		{
			motor[intake]=127;
		}

		else if (vexRT[Btn5D]==1)
		{
			motor[intake]=-127;
		}
		else
		{
			motor[intake]=15;
		}


		if (vexRT[Btn7U]==1)
		{
			motor[chainbarleft] = 127;
			motor[chainbarright] = 127;
		}
		else if (vexRT[Btn7D]==1)
		{
			motor[chainbarleft] = -127;
			motor[chainbarright] = -127;
		}
		else
		{
			motor[chainbarleft] = 0;
			motor[chainbarright] = 0;

		}

		if (vexRT[Btn6U]==1)
		{

			motor[conelift] = 127;
		}
		else if (vexRT[Btn6D]==1)
		{
			motor[conelift] = -127;
		}

		else
		{
			motor[conelift] = 0;
		}


		if (vexRT[Btn8D]==1)
		{
			stopTask(mobilepickup);
			startTask(mobileputdown);
		}

		if (vexRT[Btn8U]==1)
		{
			stopTask(mobileputdown);
			startTask(mobilepickup);

		}

	}
}
