#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    potconelift,    sensorPotentiometer)
#pragma config(Sensor, in2,    potchainbar,    sensorPotentiometer)
#pragma config(Sensor, in3,    potmobilelift,  sensorPotentiometer)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, in5,    linetracker,    sensorLineFollower)
#pragma config(Sensor, in6,    linetracker2,   sensorLineFollower)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftdrive1,    tmotorVex393HighSpeed_HBridge, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port2,           leftdrive2,    tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           conelift,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           mobilelift,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           chainbarleft,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           chainbarright, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightdrive2,   tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port10,          rightdrive1,   tmotorVex393HighSpeed_HBridge, openLoop, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


///////////////////////////////////////////////////////////////////////////////////////////////


int auton = 0;
void displayAuton(){
	switch(auton){


	case 2:

		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);
		string mainBattery, backupBattery;
		// Clear line 2 (1) of the LCD

		//Display the Primary Robot battery voltage
		displayLCDString(0, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
		displayNextLCDString(mainBattery);

		//Display the Backup battery voltage
		displayLCDString(1, 0, "Backup: ");
		sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');    //Build the value to be displayed
		displayNextLCDString(backupBattery);

		//Short delay for the LCD refresh rate
		wait1Msec(100);
		break;


	case 1:
		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);
		displayNextLCDNumber(SensorValue(I2C_1));
		displayNextLCDNumber(SensorValue(gyro));
		wait1Msec(100);
		break;


	case 0:
		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);
		displayLCDCenteredString(0, "20 point left");
		break;

	case -1:
		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);
		displayLCDCenteredString(0, "20 point right");
		break;


	case -2:
		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);
		displayLCDCenteredString(0, "5 point left");
		break;


	case -3:
		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);
		displayLCDCenteredString(0, "5 point right");
		break;

	case -4:
		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);
		displayLCDCenteredString(0, "Stationary Goal");
		break;

	case -5:
		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);
		displayLCDCenteredString(0, "Skills");
		break;

	case -6:
		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);
		displayLCDCenteredString(0, "Alone");
		break;
	}
}


//DO NOT MODIFY
task LCDControl()
{
	clearLCDLine(0);
	clearLCDLine(1);
	bLCDBacklight = true;
	bool noButtonsPressed = true;
	displayAuton();
	while(true){
		if(noButtonsPressed){ // only update auton if a button is pressed AND wasn't pressed previously
			switch(nLCDButtons){
			case kButtonLeft:
				auton--;
				displayAuton();
				break;
			case kButtonCenter:
				stopTask(LCDControl);
				break;
			case kButtonRight:
				auton++;
				displayAuton();
				break;
			}
		}//if
		noButtonsPressed = !nLCDButtons; //update if there is a button currently pressed
		wait1Msec(20);
	}//while
}//task




int value=1;

task mobilepickup()
{
	repeatUntil (SensorValue(potmobilelift)<=300)
	{
		motor[mobilelift] = 127;
	}
	motor[mobilelift] = 0;
}

task mobileputdown1()
{
	repeatUntil (SensorValue(potmobilelift)>=2300)
	{
		motor[mobilelift] = -127;
	}
	motor[mobilelift] = 0;
	value = 1;
}

task mobileputdown2()
{
	repeatUntil (SensorValue(potmobilelift)>=900)
	{
		motor[mobilelift] = -127;
	}
	motor[mobilelift] = 0;
	value = 0;
}

void movedistance (int degrees, int power)
{
	SensorValue(I2C_1) = 0;
	SensorValue(I2C_2) = 0;
	repeatUntil(abs(SensorValue(I2C_1)) >= degrees)
	{
		motor[leftdrive1] = power;
		motor[leftdrive2]  = power;
		repeatUntil (abs(SensorValue(I2C_2)) >= degrees)
		{
			motor[rightdrive2] = power;
			motor[rightdrive1]  = power;
		}
	}

	SensorValue(I2C_1) = 0;
	SensorValue(I2C_2) = 0;
	if (power > 0)
	{
		motor[leftdrive1] = -10;
		motor[leftdrive2] = -10;
		motor[rightdrive2] = -10;
		motor[rightdrive1] =-10;
	}
	else
	{
		motor[leftdrive1] = 10;
		motor[leftdrive2] = 10;
		motor[rightdrive2] = 10;
		motor[rightdrive1] = 10;
	}
}

void movedistance1 (int degrees, int power)
{
	SensorValue(I2C_1) = 0;
	SensorValue(I2C_2) = 0;
	repeatUntil(abs(SensorValue(I2C_1)) >= degrees)
	{
		motor[leftdrive1] = power;
		motor[leftdrive2]  = power;
		repeatUntil (abs(SensorValue(I2C_2)) >= degrees)
		{
			motor[rightdrive2] = power;
			motor[rightdrive1]  = power;
		}
	}

	SensorValue(I2C_1) = 0;
	SensorValue(I2C_2) = 0;
	motor[leftdrive1] = 0;
	motor[leftdrive2] = 0;
	motor[rightdrive2] = 0;
	motor[rightdrive1] = 0;
}


void gyroturn(int gyrovalue, int gyrospeed)
{
	wait1Msec(300);
	if(SensorValue(gyro)<gyrovalue)
	{
		repeatUntil(SensorValue(gyro) >=gyrovalue)
		{
			motor[leftdrive1] = -gyrospeed;
			motor[leftdrive2] = -gyrospeed;
			motor[rightdrive2] = gyrospeed;
			motor[rightdrive1] =gyrospeed;
		}
		motor[leftdrive1] = 10;
		motor[leftdrive2] = 10;
		motor[rightdrive2] = -10;
		motor[rightdrive1] =-10;
	}

	else if(SensorValue(gyro) >gyrovalue)
	{
		repeatUntil(SensorValue(gyro) <=gyrovalue)
		{
			motor[leftdrive1] = gyrospeed;
			motor[leftdrive2] = gyrospeed;
			motor[rightdrive2] = -gyrospeed;
			motor[rightdrive1] =-gyrospeed;
		}
		motor[leftdrive1] = -10;
		motor[leftdrive2] = -10;
		motor[rightdrive2] = 10;
		motor[rightdrive1] =10;
	}
	wait1Msec(300);
}

void linetrack1(int sensor, int speed)
{
	if (sensor==1)
	{
		repeatUntil(SensorValue(linetracker) <=1900)
		{
			motor[leftdrive1] = speed;
			motor[leftdrive2] = speed;
			motor[rightdrive2] = speed;
			motor[rightdrive1] =speed;
		}
		motor[leftdrive1] = 0;
		motor[leftdrive2] = 0;
		motor[rightdrive2] = 0;
		motor[rightdrive1] = 0;
	}
	if (sensor == 2)
	{
		repeatUntil(SensorValue(linetracker2) <=1900)
		{
			motor[leftdrive1] = speed;
			motor[leftdrive2] = speed;
			motor[rightdrive2] = speed;
			motor[rightdrive1] =speed;
		}
		motor[leftdrive1] = 0;
		motor[leftdrive2] = 0;
		motor[rightdrive2] = 0;
		motor[rightdrive1] = 0;
	}
}


void linetrack(int sensor, int speed)
{
	if (sensor==1)
	{
		repeatUntil(SensorValue(linetracker) <=1700)
		{
			motor[leftdrive1] = speed;
			motor[leftdrive2] = speed;
			motor[rightdrive2] = speed;
			motor[rightdrive1] =speed;
		}
		if (speed>0)
		{
			motor[leftdrive1] = -10;
			motor[leftdrive2] = -10;
			motor[rightdrive2] = -10;
			motor[rightdrive1] = -10;
		}

		if (speed<0)
		{

			motor[leftdrive1] = 10;
			motor[leftdrive2] = 10;
			motor[rightdrive2] = 10;
			motor[rightdrive1] = 10;
		}
	}
	if (sensor == 2)
	{
		repeatUntil(SensorValue(linetracker2) <=1700)
		{
			motor[leftdrive1] = speed;
			motor[leftdrive2] = speed;
			motor[rightdrive2] = speed;
			motor[rightdrive1] =speed;
		}
		if (speed>0)
		{
			motor[leftdrive1] = -10;
			motor[leftdrive2] = -10;
			motor[rightdrive2] = -10;
			motor[rightdrive1] = -10;
		}

		if (speed<0)
		{

			motor[leftdrive1] = 10;
			motor[leftdrive2] = 10;
			motor[rightdrive2] = 10;
			motor[rightdrive1] = 10;
		}
	}

}


task firstconelift()
{

	repeatUntil(SensorValue(potconelift)>= 750)
	{
		motor[conelift] = 127;
	}
	motor[conelift] = 0;

	repeatUntil(SensorValue(potchainbar) >= 850)
	{
		motor[chainbarleft] = -127;
		motor[chainbarright] = -127;
	}
	motor[chainbarleft] = 0;
	motor[chainbarright] = 0;

	repeatUntil(SensorValue(potchainbar) <= 800)
	{
		motor[chainbarleft] = 127;
		motor[chainbarright] = 127;

	}
	motor[chainbarleft] = 0;
	motor[chainbarright] = 0;



}

task firstconedrop()
{

	motor[intake] = -127;
	repeatUntil(SensorValue(potconelift)<= 700)
	{
		motor[conelift] = -127;
	}
	motor[conelift] = 0;


	motor[intake] = 0;

	repeatUntil(SensorValue(potconelift)>= 750)
	{
		motor[conelift] = 127;
	}
	motor[conelift] = 0;




}

////////////////////////////////////////////////////////////////////


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	resetMotorEncoder(leftdrive2);
	resetMotorEncoder(rightdrive2);
	SensorValue[gyro] = 0;

	bStopTasksBetweenModes = true;

	bDisplayCompetitionStatusOnLcd = false;

	startTask(LCDControl);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{

	resetMotorEncoder(leftdrive2);
	resetMotorEncoder(rightdrive2);
	SensorValue[gyro] = 0;

	stopTask(LCDControl);
	switch(auton)
	{

	case -5: //Skills

		resetMotorEncoder(leftdrive2);
		resetMotorEncoder(rightdrive2);
		SensorValue[gyro] = 0;
		wait1Msec(50);

		startTask(firstconelift);
		startTask(mobileputdown1);

		wait1Msec(500);

		movedistance1(1000,127);

		linetrack1(1,127);

		movedistance1(200,127);

		wait1Msec(500);


		startTask(mobilepickup);  ///////////////////////////first cone pickup///////////////

		wait1Msec(1500);

		startTask(firstconedrop);
		wait1Msec(250);

		movedistance1(700,-127);

		linetrack1(1,-127);

		movedistance(175,-127);


		gyroturn(330,80);

		movedistance(750,-127);

		gyroturn(1250,80);


		movedistance(450,127);

		startTask(mobileputdown1); ///////////////////////////first cone drop off/////////////////

		movedistance(275,127);
		wait1Msec(1000);

		stopTask(mobileputdown1);
		startTask(mobilepickup);
		movedistance1(450,-63);

		linetrack(1,-63);

		stopTask(mobilepickup);
		startTask(mobileputdown1);
		gyroturn(560,80);


		movedistance(300,127);

		gyroturn(-360,80);

		movedistance1(600,127);
		wait1Msec(500);
		startTask(mobilepickup); //////////////////////////second cone pickup////////////////////
		wait1Msec(500);

		gyroturn(1170,80);

		movedistance1(300,127);

		startTask(mobileputdown2);////////////////////////second cone drop off///////////////////////

		linetrack1(1,127);

		movedistance(100,127);

		movedistance1(800,-100);

		linetrack(2,-100);

		startTask(mobileputdown1);
		gyroturn(2120,80);

		movedistance1(650,127);
		wait1Msec(500);

		startTask(mobilepickup); //////////////////third cone pick up///////////////
		wait1Msec(500);

		gyroturn(1490,80);


		movedistance(400,127);

		startTask(mobileputdown2);////////////////////////third cone drop off///////////////////////

		linetrack1(1,127);


		movedistance(100,127);

		movedistance(200,-127);
		wait1Msec(250);

		motor[leftdrive1] = 40;
		motor[leftdrive2] = 40;
		motor[rightdrive2] = 40;
		motor[rightdrive1] =40;
		wait1Msec(800);

		motor[leftdrive1] = 0;
		motor[leftdrive2] = 0;
		motor[rightdrive2] = 0;
		motor[rightdrive1] =0;

		wait1Msec(500);

		startTask(mobileputdown1);

		linetrack(1,-127);

		gyroturn(-480,80);

		movedistance1(300,100);

		linetrack(2,100);

		gyroturn(-610,40);

		movedistance1(700,127);


		startTask(mobilepickup);///////////////////////fourth cone pickup/////////////////
		wait1Msec(1200);

		linetrack(1,100);


		gyroturn(250,80);

		movedistance(275,100);

		gyroturn(-500,80);



		movedistance(450,127);




		startTask(mobileputdown1); ///////////////////////////fourth cone drop off/////////////////

		movedistance(275,127);
		wait1Msec(1300);

		stopTask(mobileputdown1);
		startTask(mobilepickup);
		movedistance1(450,-63);

		linetrack(1,-63);

		stopTask(mobilepickup);
		startTask(mobileputdown1);

		gyroturn(200,80);
		startTask(mobileputdown1);
		movedistance(300,100);

		gyroturn(1100,80);

		movedistance1(600,127);
		wait1Msec(500);

		startTask(mobilepickup); /////////////////////////////////fifth cone pickup////////////////////

		repeatUntil(SensorValue(potconelift)>= 750)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		wait1Msec(500);
		gyroturn(-550,80);
		movedistance1(300,127);
		startTask(mobileputdown2); ///////////////////fifth cone drop off////////////////////////////////
		linetrack1(1,127);

		movedistance(100,127);
		movedistance(800,-127);

		gyroturn(-1200,80);

		movedistance1(1500,-127); ////////////////////////park///////////////////////////

		break;



	case -4://Stationary Goal

		motor[intake] = 20;
		repeatUntil(SensorValue(potconelift)>= 1800)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		repeatUntil(SensorValue(potchainbar) >= 3500)
		{
			motor[chainbarleft] = -127;
			motor[chainbarright] = -127;
		}
		motor[chainbarleft] = 0;
		motor[chainbarright] = 0;

		movedistance(550,40);

		wait1Msec(500);
		repeatUntil(SensorValue(potconelift)<= 1500)
		{
			motor[conelift] = -127;
		}
		motor[conelift] = 0;

		motor[intake]=-127;

		repeatUntil(SensorValue(potconelift)>= 1800)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		movedistance(550,-63);

		motor[intake]=0;



		break;

	case -3://5 point right
		motor[intake]=20;

		repeatUntil(SensorValue(potconelift)>= 800)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		startTask(mobileputdown1);

		repeatUntil(SensorValue(potchainbar) >= 850)
		{
			motor[chainbarleft] = -127;
			motor[chainbarright] = -127;
		}
		motor[chainbarleft] = 0;
		motor[chainbarright] = 0;

		repeatUntil(SensorValue(potchainbar) <= 800)
		{
			motor[chainbarleft] = 127;
			motor[chainbarright] = 127;
		}
		motor[chainbarleft] = 0;
		motor[chainbarright] = 0;

		movedistance1(1000,127);

		linetrack1(1,127);

		movedistance1(100,127);

		startTask(mobilepickup);

		wait1Msec(1500);

		repeatUntil(SensorValue(potconelift)<= 700)
		{
			motor[conelift] = -127;
		}
		motor[conelift] = 0;


		motor[intake] = -127;
		wait1Msec(250);
		motor[intake] = 0;


		movedistance(1000,-127);

		gyroturn(-1500,127);


		repeatUntil(SensorValue(potconelift)>= 800)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;


		startTask(mobileputdown1);
		wait1Msec(1500);
		movedistance(300,-127);

		break;

	case -2://5 point left
		motor[intake]=20;

		repeatUntil(SensorValue(potconelift)>= 800)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		startTask(mobileputdown1);

		repeatUntil(SensorValue(potchainbar) >= 850)
		{
			motor[chainbarleft] = -127;
			motor[chainbarright] = -127;
		}
		motor[chainbarleft] = 0;
		motor[chainbarright] = 0;

		repeatUntil(SensorValue(potchainbar) <= 800)
		{
			motor[chainbarleft] = 127;
			motor[chainbarright] = 127;
		}
		motor[chainbarleft] = 0;
		motor[chainbarright] = 0;

		movedistance1(1000,127);

		linetrack1(1,127);

		movedistance1(100,127);

		startTask(mobilepickup);

		wait1Msec(1500);

		repeatUntil(SensorValue(potconelift)<= 700)
		{
			motor[conelift] = -127;
		}
		motor[conelift] = 0;


		motor[intake] = -127;
		wait1Msec(250);
		motor[intake] = 0;


		movedistance(1000,-127);

		gyroturn(1400,127);


		repeatUntil(SensorValue(potconelift)>= 800)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;


		startTask(mobileputdown1);
		wait1Msec(1500);
		movedistance(300,-127);

		break;

	case -1://20 point right

		motor[intake]=20;

		repeatUntil(SensorValue(potconelift)>= 800)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		startTask(mobileputdown1);

		repeatUntil(SensorValue(potchainbar) >= 850)
		{
			motor[chainbarleft] = -127;
			motor[chainbarright] = -127;
		}
		motor[chainbarleft] = 0;
		motor[chainbarright] = 0;

		repeatUntil(SensorValue(potchainbar) <= 800)
		{
			motor[chainbarleft] = 127;
			motor[chainbarright] = 127;

		}
		motor[chainbarleft] = 0;
		motor[chainbarright] = 0;

		movedistance1(1000,127);

		linetrack1(1,127);

		movedistance1(100,127);

		startTask(mobilepickup);

		wait1Msec(1500);

		repeatUntil(SensorValue(potconelift)<= 700)
		{
			motor[conelift] = -127;
		}
		motor[conelift] = 0;


		motor[intake] = -127;
		wait1Msec(250);
		motor[intake] = 0;



		movedistance1(900,-127);

		linetrack1(1,-127);

		movedistance(175,-127);


		gyroturn(-330,127);


		movedistance(700,-127);

		gyroturn(-1270,127);


		movedistance(700,127);

		startTask(mobileputdown1);
		repeatUntil(SensorValue(potconelift)>= 800)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;


		wait1Msec(1300);

		repeatUntil(SensorValue(potconelift)>= 800)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		stopTask(mobileputdown1);
		startTask(mobilepickup);
		movedistance(400,-127);



		break;

	case 0://20 point left
		motor[intake]=20;

		repeatUntil(SensorValue(potconelift)>= 800)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		startTask(mobileputdown1);

		repeatUntil(SensorValue(potchainbar) >= 850)
		{
			motor[chainbarleft] = -127;
			motor[chainbarright] = -127;
		}
		motor[chainbarleft] = 0;
		motor[chainbarright] = 0;

		repeatUntil(SensorValue(potchainbar) <= 800)
		{
			motor[chainbarleft] = 127;
			motor[chainbarright] = 127;

		}
		motor[chainbarleft] = 0;
		motor[chainbarright] = 0;

		movedistance1(1000,127);

		linetrack1(1,127);

		movedistance1(100,127);

		startTask(mobilepickup);

		wait1Msec(1500);

		repeatUntil(SensorValue(potconelift)<= 700)
		{
			motor[conelift] = -127;
		}
		motor[conelift] = 0;


		motor[intake] = -127;
		wait1Msec(250);
		motor[intake] = 0;



		movedistance1(900,-127);

		linetrack1(1,-127);

		movedistance(175,-127);


		gyroturn(300,127);


		movedistance(700,-127);

		gyroturn(1240,127);


		movedistance(700,127);

		startTask(mobileputdown1);
		repeatUntil(SensorValue(potconelift)>= 800)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;


		wait1Msec(1300);

		stopTask(mobileputdown1);
		startTask(mobilepickup);
		movedistance(400,-127);


		break;

	case 1://do nothing

		break;

	case 2://do nothing

		break;

	case -6://do nothing

		break;
	}
}


task usercontrol()
{
	stopTask(LCDControl);
	switch(auton)
	{
	default:

		while (true)
		{
			motor[leftdrive1] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
			motor[leftdrive2] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
			motor[rightdrive2] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;
			motor[rightdrive1] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;

			if (vexRT[Btn6D]==1)
			{
				stopTask(mobilepickup);
				startTask(mobileputdown1);
			}

			if (vexRT[Btn6U]==1)
			{
				stopTask(mobileputdown1);
				startTask(mobilepickup);
			}

			if (vexRT[Btn5UXmtr2]==1)
			{
				motor[intake]=127;
			}

			else if (vexRT[Btn5DXmtr2]==1)
			{
				motor[intake]=-127;
			}
			else
			{
				motor[intake]=15;
			}


			if (vexRT[Btn7UXmtr2]==1)
			{
				motor[chainbarleft] = 127;
				motor[chainbarright] = 127;
			}
			else if (vexRT[Btn7DXmtr2]==1)
			{
				motor[chainbarleft] = -127;
				motor[chainbarright] = -127;
			}
			else
			{
				motor[chainbarleft] = 0;
				motor[chainbarright] = 0;
			}


			if (vexRT[Btn6UXmtr2]==1)
			{
				motor[conelift] = 127;
			}
			else if (vexRT[Btn6DXmtr2]==1)
			{
				motor[conelift] = -127;
			}

			else
			{
				motor[conelift] = 0;
			}

		}
		break;

	case -5:
		while (true)
		{
			motor[leftdrive1] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
			motor[leftdrive2] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
			motor[rightdrive2] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;
			motor[rightdrive1] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;

			if (vexRT[Btn5U]==1)
			{
				stopTask(firstconedrop);
				startTask(firstconelift);
			}
			if (vexRT[Btn5D]==1)
			{
				stopTask(firstconelift);
				startTask(firstconedrop);
			}



			if (vexRT[Btn6D]==1)
			{
				stopTask(mobilepickup);

				if (value==1)
				{
					startTask(mobileputdown2);
				}

				if (value==0)
				{
					startTask(mobileputdown1);
				}
			}

			if (vexRT[Btn6U]==1)
			{
				stopTask(mobileputdown1);
				stopTask(mobileputdown2);
				startTask(mobilepickup);
			}

		}

		break;

	case -6:

		while (true)
		{

			motor[leftdrive1] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
			motor[leftdrive2] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
			motor[rightdrive2] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;
			motor[rightdrive1] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;


			if (vexRT[Btn5U]==1)
			{
				motor[intake]=127;
			}

			else if (vexRT[Btn5D]==1)
			{
				motor[intake]=-127;
			}
			else
			{
				motor[intake]=15;
			}


			if (vexRT[Btn7U]==1)
			{
				motor[chainbarleft] = 127;
				motor[chainbarright] = 127;
			}
			else if (vexRT[Btn7D]==1)
			{
				motor[chainbarleft] = -127;
				motor[chainbarright] = -127;
			}
			else
			{
				motor[chainbarleft] = 0;
				motor[chainbarright] = 0;

			}

			if (vexRT[Btn6U]==1)
			{

				motor[conelift] = 127;
			}
			else if (vexRT[Btn6D]==1)
			{
				motor[conelift] = -127;
			}

			else
			{
				motor[conelift] = 0;
			}


			if (vexRT[Btn8D]==1)
			{
				stopTask(mobilepickup);
				startTask(mobileputdown1);
			}

			if (vexRT[Btn8U]==1)
			{
				stopTask(mobileputdown1);
				startTask(mobilepickup);

			}

		}


		break;

	}
}
