#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    potentiometermogo, sensorPotentiometer)
#pragma config(Sensor, in2,    linefolllower,  sensorLineFollower)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl11, ,               sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftdrive1,    tmotorVex393HighSpeed_HBridge, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port2,           leftdrive2,    tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           intake,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           chainbar,      tmotorVex393_MC29, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port5,           mobilelift,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           conelift,      tmotorVex393_MC29, openLoop, encoderPort, dgtl11)
#pragma config(Motor,  port9,           rightdrive2,   tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port10,          rightdrive1,   tmotorVex393HighSpeed_HBridge, openLoop, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#include "SmartMotorLib.c"

///////////////////////////////////////////////////////////////////////////////////////////////


int auton = 0;


//ADD all autonomous choices
void displayAuton(){
	switch(auton){
	case 1:
		displayLCDCenteredString(0, "20 point zone");
		break;
	case -1:
		displayLCDCenteredString(0, "5 point zone");
		break;
	case 0:
		displayLCDCenteredString(0, "Stationary Goal");
		break;
	default:
		displayLCDCenteredString(0, "None");
		break;
	}
}


//DO NOT MODIFY
task LCDControl()
{
	clearLCDLine(0);
	clearLCDLine(1);
	bLCDBacklight = true;
	bool noButtonsPressed = true;
	displayAuton();
	while(true){
		if(noButtonsPressed){ // only update auton if a button is pressed AND wasn't pressed previously
			switch(nLCDButtons){
			case kButtonLeft:
				auton--;
				displayAuton();
				break;
			case kButtonCenter:
				stopTask(LCDControl);
				break;
			case kButtonRight:
				auton++;
				displayAuton();
				break;
			}
		}//if
		noButtonsPressed = !nLCDButtons; //update if there is a button currently pressed
		wait1Msec(20);
	}//while
}//task







void movedistance (int degrees, int power)
{
	SensorValue(I2C_1) = 0;
	SensorValue(I2C_2) = 0;

	repeatUntil(abs(SensorValue(I2C_1)) >= degrees)
	{
		motor[leftdrive1] = power;
		motor[leftdrive2]  = power;
		repeatUntil (abs(SensorValue(I2C_2)) >= degrees)
		{
			motor[rightdrive2] = power;
			motor[rightdrive1]  = power;
		}
	}
	SensorValue(I2C_1) = 0;
	SensorValue(I2C_2) = 0;
	motor[leftdrive1] = 0;
	motor[leftdrive2] = 0;
	motor[rightdrive2] = 0;
	motor[rightdrive1] =0;

}

void turndistance (int degrees, int power)
{
	SensorValue(I2C_1) = 0;
	SensorValue(I2C_2) = 0;

	repeatUntil(abs(SensorValue(I2C_1)) >= degrees)
	{
		motor[leftdrive1] = power;
		motor[leftdrive2]  = power;
		repeatUntil (abs(SensorValue(I2C_2)) >= degrees)
		{
			motor[rightdrive2] = -power;
			motor[rightdrive1]  = -power;
		}
	}
	SensorValue(I2C_1) = 0;
	SensorValue(I2C_2) = 0;
	motor[leftdrive1] = 0;
	motor[leftdrive2] = 0;
	motor[rightdrive2] = 0;
	motor[rightdrive1] =0;
}

task mobilepickup()
{


	repeatUntil (SensorValue(in1)<=500)
	{
		motor[mobilelift] = 127;
	}
	motor[mobilelift] = 0;
}

task mobileputdown()
{
	repeatUntil (SensorValue(in1)>=2070)
	{
		motor[mobilelift] = -127;
	}
	motor[mobilelift] = 0;
}

////////////////////////////////////////////////////////////////////


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	resetMotorEncoder(leftdrive2);
	resetMotorEncoder(rightdrive2);
	resetMotorEncoder(chainbar);
	resetMotorEncoder(conelift);
	SensorValue[in3] = 0;

	bStopTasksBetweenModes = true;

	bDisplayCompetitionStatusOnLcd = false;

	startTask(LCDControl);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{

	resetMotorEncoder(leftdrive2);
	resetMotorEncoder(rightdrive2);
	resetMotorEncoder(chainbar);
	resetMotorEncoder(conelift);
	SensorValue[in3] = 0;




	stopTask(LCDControl);
	switch(auton){
	case 1:



		repeatUntil(SensorValue(dgtl1) <= -350)
		{
			motor[chainbar] = -127;
		}
		motor[chainbar] = 0;

		repeatUntil(SensorValue(dgtl1) >= -310)
		{
			motor[chainbar] = 127;
		}
		motor[chainbar] = 0;

		repeatUntil(SensorValue(dgtl11)>= 20)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		startTask(mobileputdown);


		movedistance(1000,127);

		repeatUntil(SensorValue(in2) <=500)
		{
			motor[leftdrive1] = 127;
			motor[leftdrive2] = 127;
			motor[rightdrive2] = 127;
			motor[rightdrive1] =127;
		}
		motor[leftdrive1] = 0;
		motor[leftdrive2] = 0;
		motor[rightdrive2] = 0;
		motor[rightdrive1] =0;

		startTask(mobilepickup);
		wait1Msec(1000);

		repeatUntil(SensorValue(dgtl11)<= 5)
		{
			motor[conelift] = -127;
		}
		motor[conelift] = 0;

		motor[intake] = -127;
		wait1Msec(800);
		motor[intake] = 0;


		repeatUntil(SensorValue(dgtl11)>= 20)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;


		movedistance(1000,-127);

		repeatUntil(SensorValue(in2) <=500)
		{
			motor[leftdrive1] = -127;
			motor[leftdrive2] = -127;
			motor[rightdrive2] = -127;
			motor[rightdrive1] =-127;
		}
		motor[leftdrive1] = 0;
		motor[leftdrive2] = 0;
		motor[rightdrive2] = 0;
		motor[rightdrive1] =0;

		wait1Msec(1000);

		turndistance(170,127);
		wait1Msec(100);
		movedistance(420,-127);
		wait1Msec(100);
		turndistance(195,127);
		wait1Msec(100);
		movedistance(300,127);
		wait1Msec(100);

		startTask(mobileputdown);
		wait1Msec(1000);

		movedistance(50,-127);
		startTask(mobilepickup);

		break;

	case 0:

		repeatUntil(SensorValue(dgtl1) <= -350)
		{
			motor[chainbar] = -127;
		}
		motor[chainbar] = 0;

		repeatUntil(SensorValue(dgtl1) >= -310)
		{
			motor[chainbar] = 127;
		}
		motor[chainbar] = 0;

		repeatUntil(SensorValue(dgtl11)>= 75)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		repeatUntil(SensorValue(dgtl1) <= -900)
		{
			motor[chainbar] = -127;
		}
		motor[chainbar] = 0;

		movedistance(425,32);

		wait1Msec(1000);

		motor[intake] = -127;
		wait1Msec(1000);
		motor[intake] = 0;

		movedistance(425,-32);

		break;

	case -1:

		repeatUntil(SensorValue(dgtl1) <= -350)
		{
			motor[chainbar] = -127;
		}
		motor[chainbar] = 0;

		repeatUntil(SensorValue(dgtl1) >= -310)
		{
			motor[chainbar] = 127;
		}
		motor[chainbar] = 0;



		repeatUntil(SensorValue(dgtl11)>= 20)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		startTask(mobileputdown);



		movedistance(1000,127);

		repeatUntil(SensorValue(in2) <=500)
		{
			motor[leftdrive1] = 127;
			motor[leftdrive2] = 127;
			motor[rightdrive2] = 127;
			motor[rightdrive1] =127;
		}
		motor[leftdrive1] = 0;
		motor[leftdrive2] = 0;
		motor[rightdrive2] = 0;
		motor[rightdrive1] =0;

		startTask(mobilepickup);
		wait1Msec(1000);

		repeatUntil(SensorValue(dgtl11)<= 5)
		{
			motor[conelift] = -127;
		}
		motor[conelift] = 0;

		motor[intake] = -127;
		wait1Msec(800);
		motor[intake] = 0;


		repeatUntil(SensorValue(dgtl11)>= 20)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;


		movedistance(1200,-127);

		turndistance(700,-127);
		wait1Msec(100);


		startTask(mobileputdown);
		wait1Msec(1000);

		movedistance(200,-127);

		break;
	default:
		//Don't run auton
		break;
	}

}


task usercontrol()
{

	stopTask(LCDControl);

	while (true)
	{

		motor[leftdrive1] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
		motor[leftdrive2] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
		motor[rightdrive2] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;
		motor[rightdrive1] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;

		if (vexRT[Btn6U]==1)
		{
			motor[conelift] = 127;
			wait1Msec(20);

		}
		else if (vexRT[Btn6D]==1)
		{
			motor[conelift] = -127;
			wait1Msec(20);

		}
		else
		{
			motor[conelift] = 0;
			wait1Msec(20);

		}



		if (vexRT[Btn5U]==1)
		{
			motor[intake]=127;
		}

		else if (vexRT[Btn5D]==1)
		{
			motor[intake]=-127;
		}
		else
		{
			motor[intake]=0;
		}


		if (vexRT[Btn7U]==1)
		{
			motor[chainbar] = 127;

		}
		else if (vexRT[Btn7D]==1)
		{
			motor[chainbar]=-127;
		}

		else
		{
			if(SensorValue(dgtl1) < -710 && SensorValue(dgtl1) >-900)
			{
				motor[chainbar]=20;
			}
			else
			{
				motor[chainbar]=0;
			}
		}



		if (vexRT[Btn8D]==1)
		{
			startTask(mobileputdown);
		}

		if (vexRT[Btn8U]==1)
		{
			startTask(mobilepickup);

		}
	}
}
