#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    linetrackright, sensorLineFollower)
#pragma config(Sensor, in3,    linetrackleft,  sensorLineFollower)
#pragma config(Sensor, dgtl1,  sonicsensorleft, sensorSONAR_raw)
#pragma config(Sensor, dgtl3,  sonicsensorright, sensorSONAR_raw)
#pragma config(Sensor, dgtl5,  liftencoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  mogoencoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl11, driveencoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           rightdrive1,   tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           rightdrive2,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           fourbarleft,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           mobilelift,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           conelift,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           intake,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           fourbarright,  tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftdrive2,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftdrive1,    tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
#include "SlewRateTask.c"

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


int auton = 0;
void displayAuton(){
	switch(auton){

	case 2:

		clearLCDLine(0);
		clearLCDLine(1);
		displayNextLCDNumber(SensorValue(gyro));

		break;

	case 1:

		clearLCDLine(0);
		clearLCDLine(1);
		string mainBattery, backupBattery;
		displayLCDString(0, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V');
		displayNextLCDString(mainBattery);
		displayLCDString(1, 0, "Backup: ");
		sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');
		displayNextLCDString(backupBattery);

		wait1Msec(100);
		break;


	case 0:
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDCenteredString(0, "20 point left");
		break;

	case -1:
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDCenteredString(0, "20 point right");
		break;


	case -2:
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDCenteredString(0, "5 point left");
		break;


	case -3:
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDCenteredString(0, "5 point right");
		break;

	case -4:
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDCenteredString(0, "Skills");
		break;



	case -5:
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDCenteredString(0, "Alone");
		break;

	case -6:
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDCenteredString(0, "Skills Alone");
		break;

	}
}




void movedistance (int degrees, int power, int type)
{
	SensorValue(driveencoder) = 0;
	repeatUntil(abs(SensorValue(driveencoder)) >= degrees)
	{
		motorReq[leftdrive1] = power;
		motorReq[leftdrive2]  = power;
		motorReq[rightdrive1] = power;
		motorReq[rightdrive2]  = power;
	}
	SensorValue(driveencoder) = 0;

	if (type==1)
	{
		if (power > 0)
		{
			motorReq[leftdrive1] = -10;
			motorReq[leftdrive2] = -10;
			motorReq[rightdrive2] = -10;
			motorReq[rightdrive1] =-10;
		}
		else
		{
			motorReq[leftdrive1] = 10;
			motorReq[leftdrive2] = 10;
			motorReq[rightdrive2] = 10;
			motorReq[rightdrive1] = 10;
		}
	}
	else if (type==2)
	{
		motorReq[leftdrive1] = 0;
		motorReq[leftdrive2] = 0;
		motorReq[rightdrive2] = 0;
		motorReq[rightdrive1] = 0;
	}
}


void gyroturn(int gyrovalue, int gyrospeed)
{
	wait1Msec(300);
	if(SensorValue(gyro)<gyrovalue)
	{
		repeatUntil(SensorValue(gyro) >=(gyrovalue))
		{
			motor[leftdrive1] = -gyrospeed;
			motor[leftdrive2] = -gyrospeed;
			motor[rightdrive2] = gyrospeed;
			motor[rightdrive1] =gyrospeed;
		}
		motor[leftdrive1] = 30;
		motor[leftdrive2] = 30;
		motor[rightdrive2] = -30;
		motor[rightdrive1] =-30;
	}

	else if(SensorValue(gyro) >gyrovalue)
	{
		repeatUntil(SensorValue(gyro) <=(gyrovalue))
		{
			motor[leftdrive1] = gyrospeed;
			motor[leftdrive2] = gyrospeed;
			motor[rightdrive2] = -gyrospeed;
			motor[rightdrive1] =-gyrospeed;
		}
		motor[leftdrive1] = -30;
		motor[leftdrive2] = -30;
		motor[rightdrive2] = 30;
		motor[rightdrive1] =30;
	}
	wait1Msec(300);
}

void linetrack(int sensor, int speed)
{
	if (sensor==1)
	{
		repeatUntil(SensorValue(linetrackleft) <=1000)
		{
			motorReq[leftdrive1] = speed;
			motorReq[leftdrive2] = speed;
			motorReq[rightdrive2] = speed;
			motorReq[rightdrive1] =speed;
		}
		motorReq[leftdrive1] = 0;
		motorReq[leftdrive2] = 0;
		motorReq[rightdrive2] = 0;
		motorReq[rightdrive1] = 0;
	}
	if (sensor == 2)
	{
		repeatUntil(SensorValue(linetrackright) <=1000)
		{
			motorReq[leftdrive1] = speed;
			motorReq[leftdrive2] = speed;
			motorReq[rightdrive2] = speed;
			motorReq[rightdrive1] =speed;
		}

		motorReq[leftdrive1] = 0;
		motorReq[leftdrive2] = 0;
		motorReq[rightdrive2] = 0;
		motorReq[rightdrive1] = 0;

	}
}




int value = 1;
task mobilepickup()
{
	repeatUntil (SensorValue(mogoencoder)<=5)
	{
		motor[mobilelift] = 127;
	}
	motor[mobilelift] = 0;
}

task mobilepickup2()
{
	repeatUntil (SensorValue(mogoencoder)<=80)
	{
		motor[mobilelift] = 127;
	}
	motor[mobilelift] = 0;

}

task mobileputdown1()
{

	repeatUntil (SensorValue(mogoencoder)>=135)
	{
		motor[mobilelift] = -127;
	}
	motor[mobilelift] = 0;
	value = 1;
}

task mobileputdown2()
{

	repeatUntil (SensorValue(mogoencoder)>=45)
	{
		motor[mobilelift] = -127;
	}
	motor[mobilelift] = 0;
	value = 0;
}



task firstconelift()
{
	repeatUntil(SensorValue(liftencoder)<= -3)
	{
		motor[conelift] = 127;
	}
	motor[conelift] = 0;
}


task firstconedrop()
{


	repeatUntil(SensorValue(liftencoder)>= -5)
	{
		motor[conelift] = -127;
	}
	motor[conelift] = 0;

	motorReq[intake] = -127;
	wait1Msec(250);

	repeatUntil(SensorValue(liftencoder)<= -3)
	{
		motor[conelift] = 127;
	}
	motor[conelift] = 0;

	motorReq[intake] = 0;
}

task LCDControl()
{
	clearLCDLine(0);
	clearLCDLine(1);
	bLCDBacklight = true;
	bool noButtonsPressed = true;
	displayAuton();
	while(true){
		if(noButtonsPressed){ // only update auton if a button is pressed AND wasn't pressed previously
			switch(nLCDButtons){
			case kButtonLeft:
				auton--;
				displayAuton();
				break;
			case kButtonCenter:
				stopTask(LCDControl);
				break;
			case kButtonRight:
				auton++;
				displayAuton();
				break;
			}
		}//if
		noButtonsPressed = !nLCDButtons; //update if there is a button currently pressed
		wait1Msec(20);
	}//while
}//task



//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////






void pre_auton()
{

	SensorValue[gyro] = 0;
	SensorValue[liftencoder] = 0;
	SensorValue[mogoencoder] = 0;
	SensorValue[driveencoder] = 0;


	bStopTasksBetweenModes = true;

	bDisplayCompetitionStatusOnLcd = false;

	startTask(LCDControl);


}


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


task autonomous()
{
	SensorValue[gyro] = 0;
	SensorValue[liftencoder] = 0;
	SensorValue[mogoencoder] = 0;
	SensorValue[driveencoder] = 0;

	stopTask(LCDControl);


	startTask(MotorSlewRateTask);
	motorSlew[leftdrive1] = 20;
	motorSlew[rightdrive1] = 20;
	motorSlew[leftdrive2] = 20;
	motorSlew[rightdrive1] = 20;
	motorSlew[fourbarleft] = 127;
	motorSlew[fourbarright] =127;
	motorSlew[intake] = 127;


	switch(auton)
	{

		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
		//20POINTLEFT 20POINTLEFT 20POINTLEFT 20POINTLEFT 20POINTLEFT 20POINTLEFT 20POINTLEFT 20POINTLEFT 20POINTLEFT 20POINTL
		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

	case 0:

		clearTimer(T1);
		clearLCDLine(0);
		clearLCDLine(1);

		motorReq[intake]=30;
		startTask(firstconelift);

		startTask(mobileputdown1);
		wait1Msec(750);

		movedistance(100,63,2);

		movedistance(400,127,2);

		linetrack(2,127);

		wait1Msec(250);

		startTask(mobilepickup);

		wait1Msec(1500);

		repeatUntil(SensorValue(liftencoder)>= -5)
		{
			motor[conelift] = -127;
		}
		motor[conelift] = 0;

		motorReq[intake]=-127;

		movedistance(50,127,1);

		repeatUntil(SensorValue(liftencoder)<= -5)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;


		motorReq[fourbarleft] = -127;
		motorReq[fourbarright] = -127;

		wait1Msec(400);

		motorReq[fourbarleft] = 0;
		motorReq[fourbarright] = 0;

		motorReq[intake]=127;

		repeatUntil(SensorValue(liftencoder)>= -3)
		{
			motor[conelift] = -127;
		}
		motor[conelift] = 0;

		wait1Msec(500);

		repeatUntil(SensorValue(liftencoder)<= -5)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		motorReq[fourbarleft] = 127;
		motorReq[fourbarright] = 127;

		wait1Msec(500);

		motorReq[fourbarleft] = 0;
		motorReq[fourbarright] = 0;

		repeatUntil(SensorValue(liftencoder)>= -5)
		{
			motor[conelift] = -127;
		}
		motor[conelift] = 0;

		motorReq[intake]=0;

		movedistance(600,-127,2);

		linetrack(2,-127);

		movedistance(1,-127,1);

		gyroturn(250,127);

		repeatUntil(SensorValue(sonicsensorleft)>=3000)
		{
			motorReq[leftdrive1] = -127;
			motorReq[leftdrive2] = -127;
			motorReq[rightdrive2] = -127;
			motorReq[rightdrive1] =-127;
		}

		motorReq[leftdrive1] = 10;
		motorReq[leftdrive2] = 10;
		motorReq[rightdrive2] = 10;
		motorReq[rightdrive1] = 10;

		gyroturn(1140,127);

		motorReq[intake]=-127;

		wait1Msec(250);


		repeatUntil(SensorValue(liftencoder)<= -10)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		startTask(mobileputdown1);

		movedistance(450,63,2);

		wait1Msec(500);

		movedistance(500,-127,1);

		displayNextLCDNumber(time1[T1]);

		break;

		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
		//20POINTRIGHT 20POINTRIGHT 20POINTRIGHT 20POINTRIGHT 20POINTRIGHT 20POINTRIGHT 20POINTRIGHT 20POINTRIGHT 20POINTRIGHT
		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

	case -1:

		clearTimer(T1);
		clearLCDLine(0);
		clearLCDLine(1);

		motorReq[intake]=30;
		startTask(firstconelift);

		startTask(mobileputdown1);
		wait1Msec(750);

		movedistance(100,63,2);

		movedistance(400,127,2);

		linetrack(1,127);

		wait1Msec(250);

		startTask(mobilepickup);

		wait1Msec(1500);

		repeatUntil(SensorValue(liftencoder)>= -5)
		{
			motor[conelift] = -127;
		}
		motor[conelift] = 0;

		motorReq[intake]=-127;

		movedistance(50,127,1);

		repeatUntil(SensorValue(liftencoder)<= -5)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		motorReq[fourbarleft] = -127;
		motorReq[fourbarright] = -127;

		wait1Msec(400);

		motorReq[fourbarleft] = 0;
		motorReq[fourbarright] = 0;

		motorReq[intake]=127;

		repeatUntil(SensorValue(liftencoder)>= -3)
		{
			motor[conelift] = -127;
		}
		motor[conelift] = 0;

		wait1Msec(500);

		repeatUntil(SensorValue(liftencoder)<= -5)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		motorReq[fourbarleft] = 127;
		motorReq[fourbarright] = 127;

		wait1Msec(500);

		motorReq[fourbarleft] = 0;
		motorReq[fourbarright] = 0;

		repeatUntil(SensorValue(liftencoder)>= -5)
		{
			motor[conelift] = -127;
		}
		motor[conelift] = 0;

		motorReq[intake]=0;

		movedistance(600,-127,2);

		linetrack(1,-127);

		movedistance(1,-127,1);

		gyroturn(-290,127);

		repeatUntil(SensorValue(sonicsensorright)>=3000)
		{
			motorReq[leftdrive1] = -127;
			motorReq[leftdrive2] = -127;
			motorReq[rightdrive2] = -127;
			motorReq[rightdrive1] =-127;
		}

		motorReq[leftdrive1] = 10;
		motorReq[leftdrive2] = 10;
		motorReq[rightdrive2] = 10;
		motorReq[rightdrive1] = 10;

		gyroturn(-1180,127);

		motorReq[intake]=-127;

		wait1Msec(250);

		repeatUntil(SensorValue(liftencoder)<= -10)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		startTask(mobileputdown1);

		movedistance(450,63,2);

		wait1Msec(500);

		movedistance(500,-127,1);

		displayNextLCDNumber(time1[T1]);

		break;

		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
		//5POINTLEFT 5POINTLEFT 5POINTLEFT 5POINTLEFT 5POINTLEFT 5POINTLEFT 5POINTLEFT 5POINTLEFT 5POINTLEFT 5POINTLEFT 5POINT
		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


	case -2:

		clearTimer(T1);
		clearLCDLine(0);
		clearLCDLine(1);

		motorReq[intake]=30;
		startTask(firstconelift);

		startTask(mobileputdown1);
		wait1Msec(750);

		movedistance(100,63,2);

		movedistance(400,127,2);

		linetrack(2,127);

		wait1Msec(250);

		startTask(mobilepickup);

		wait1Msec(1500);

		repeatUntil(SensorValue(liftencoder)>= -5)
		{
			motor[conelift] = -127;
		}
		motor[conelift] = 0;

		motorReq[intake]=-127;

		movedistance(50,127,1);

		repeatUntil(SensorValue(liftencoder)<= -5)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		motorReq[fourbarleft] = -127;
		motorReq[fourbarright] = -127;

		wait1Msec(400);

		motorReq[fourbarleft] = 0;
		motorReq[fourbarright] = 0;

		motorReq[intake]=127;

		repeatUntil(SensorValue(liftencoder)>= -3)
		{
			motor[conelift] = -127;
		}
		motor[conelift] = 0;

		wait1Msec(500);

		repeatUntil(SensorValue(liftencoder)<= -5)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		motorReq[fourbarleft] = 127;
		motorReq[fourbarright] = 127;

		wait1Msec(500);

		motorReq[fourbarleft] = 0;
		motorReq[fourbarright] = 0;

		repeatUntil(SensorValue(liftencoder)>= -5)
		{
			motor[conelift] = -127;
		}
		motor[conelift] = 0;

		motorReq[intake]=0;

		movedistance(600,-127,2);

		linetrack(1,-127);

		movedistance(1,-127,1);

		gyroturn(1200,127);

		motorReq[intake]=-127;

		wait1Msec(250);

		repeatUntil(SensorValue(liftencoder)<= -10)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		startTask(mobileputdown1);

		wait1Msec(1500);

		movedistance(1800,-127,2);

		displayNextLCDNumber(time1[T1]);

		break;

		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
		//5POINTRIGHT 5POINTRIGHT 5POINTRIGHT 5POINTRIGHT 5POINTRIGHT 5POINTRIGHT 5POINTRIGHT 5POINTRIGHT 5POINTRIGHT 5POINTRI
		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

	case -3:

		clearTimer(T1);
		clearLCDLine(0);
		clearLCDLine(1);

		motorReq[intake]=30;
		startTask(firstconelift);

		startTask(mobileputdown1);
		wait1Msec(750);

		movedistance(100,63,2);

		movedistance(400,127,2);

		linetrack(1,127);

		wait1Msec(250);

		startTask(mobilepickup);

		wait1Msec(1500);

		repeatUntil(SensorValue(liftencoder)>= -5)
		{
			motor[conelift] = -127;
		}
		motor[conelift] = 0;

		motorReq[intake]=-127;

		movedistance(50,127,1);

		repeatUntil(SensorValue(liftencoder)<= -5)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		motorReq[fourbarleft] = -127;
		motorReq[fourbarright] = -127;

		wait1Msec(400);

		motorReq[fourbarleft] = 0;
		motorReq[fourbarright] = 0;

		motorReq[intake]=127;

		repeatUntil(SensorValue(liftencoder)>= -3)
		{
			motor[conelift] = -127;
		}
		motor[conelift] = 0;

		wait1Msec(500);

		repeatUntil(SensorValue(liftencoder)<= -5)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		motorReq[fourbarleft] = 127;
		motorReq[fourbarright] = 127;

		wait1Msec(500);

		motorReq[fourbarleft] = 0;
		motorReq[fourbarright] = 0;

		repeatUntil(SensorValue(liftencoder)>= -5)
		{
			motor[conelift] = -127;
		}
		motor[conelift] = 0;

		motorReq[intake]=0;

		movedistance(600,-127,2);

		linetrack(2,-127);

		movedistance(1,-127,1);

		gyroturn(-1240,127);

		motorReq[intake]=-127;

		wait1Msec(250);

		repeatUntil(SensorValue(liftencoder)<= -10)
		{
			motor[conelift] = 127;
		}
		motor[conelift] = 0;

		startTask(mobileputdown1);

		wait1Msec(1500);

		movedistance(1800,-127,2);

		displayNextLCDNumber(time1[T1]);

		break;

		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
		//SKILLS SKILLS SKILLS SKILLS SKILLS SKILLS SKILLS SKILLS SKILLS SKILLS SKILLS SKILLS SKILLS SKILLS SKILLS SKILLS SKIL
		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
		//xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


	case -4:


		clearTimer(T1);
		clearLCDLine(0);
		clearLCDLine(1);

		motorReq[intake]=30;
		startTask(firstconelift);

		startTask(mobileputdown1);
		wait1Msec(750);

		movedistance(500,127,2);

		linetrack(2,127);

		wait1Msec(250);

		startTask(mobilepickup);

		wait1Msec(1700);

		startTask(firstconedrop);


		movedistance(600,-127,2);

		linetrack(2,-127);

		movedistance(1,-127,1);

		motorReq[intake]=0;

		gyroturn(250,127);

		repeatUntil(SensorValue(sonicsensorleft)>=3000)
		{
			motorReq[leftdrive1] = -127;
			motorReq[leftdrive2] = -127;
			motorReq[rightdrive2] = -127;
			motorReq[rightdrive1] =-127;
		}

		motorReq[leftdrive1] = 10;
		motorReq[leftdrive2] = 10;
		motorReq[rightdrive2] = 10;
		motorReq[rightdrive1] = 10;

		gyroturn(1140,127);


		startTask(mobileputdown1);////////////////////////////////////first cone deposit////////////////////////

		movedistance(450,63,2);

		wait1Msec(500);

		movedistance(300,-127,1);

		wait1Msec(500);

		motorReq[leftdrive1] = 40;
		motorReq[leftdrive2] = 40;
		motorReq[rightdrive2] = 40;
		motorReq[rightdrive1] = 40;
		wait1Msec(500);

		motorReq[leftdrive1] = 0;
		motorReq[leftdrive2] = 0;
		motorReq[rightdrive2] = 0;
		motorReq[rightdrive1] = 0;
		SensorValue(driveencoder)=0;


		SensorValue(gyro)=0;

		wait1Msec(200);

		linetrack(1,-127);
		movedistance(1,-127,1);

		gyroturn(-550,100);

		gyroturn(-900,40);


		repeatUntil(SensorValue(sonicsensorleft)<=3000)
		{
			motorReq[leftdrive1] = 127;
			motorReq[leftdrive2] = 127;
			motorReq[rightdrive2] = 127;
			motorReq[rightdrive1] = 127;
		}

		motorReq[leftdrive1] = -10;
		motorReq[leftdrive2] = -10;
		motorReq[rightdrive2] = -10;
		motorReq[rightdrive1] = -10;

		wait1Msec(250);

		gyroturn(-1420,100);
		gyroturn(-1850,40);

		movedistance(500,127,2);

		startTask(mobilepickup);//////////////////////////////////////////////second cone pickup/////////////////////

		wait1Msec(600);

		gyroturn(-375,100);
		gyroturn(-30,40);

		stopTask(mobilepickup);
		startTask(mobileputdown1);/////////////////////////////second cone deposit//////////////////
		movedistance(400,127,1);
		linetrack(1,127);

		wait1Msec(500);

		movedistance(100,-63,1);
		startTask(mobilepickup2);
		wait1Msec(250);


		motorReq[leftdrive1] = 35;
		motorReq[leftdrive2] = 35;
		motorReq[rightdrive2] = 35;
		motorReq[rightdrive1] = 35;
		wait1Msec(900);

		motorReq[leftdrive1] = 0;
		motorReq[leftdrive2] = 0;
		motorReq[rightdrive2] = 0;
		motorReq[rightdrive1] = 0;
		SensorValue(driveencoder)=0;


		SensorValue(gyro)=0;

		wait1Msec(200);

		linetrack(1,-127);
		movedistance(1,-127,1);

		stopTask(mobilepickup2);
		startTask(mobileputdown1);
		gyroturn(575,100);

		gyroturn(925,40);

		repeatUntil(SensorValue(sonicsensorright)<=3300)
		{
			motorReq[leftdrive1] = 127;
			motorReq[leftdrive2] = 127;
			motorReq[rightdrive2] = 127;
			motorReq[rightdrive1] = 127;
		}

		motorReq[leftdrive1] = -10;
		motorReq[leftdrive2] = -10;
		motorReq[rightdrive2] = -10;
		motorReq[rightdrive1] = -10;

		SensorValue(driveencoder)=0;

		wait1Msec(250);

		gyroturn(1550,100);
		gyroturn(1875,40);

		movedistance(500,127,2);

		startTask(mobilepickup);//////////////////////////////////////////////third cone pickup/////////////////////

		wait1Msec(600);

		gyroturn(350,100);
		gyroturn(-30,40);


		stopTask(mobilepickup);
		startTask(mobileputdown1);/////////////////////////////third cone deposit//////////////////
		movedistance(400,127,1);
		linetrack(1,127);

		wait1Msec(500);

		motorReq[leftdrive1] = 40;
		motorReq[leftdrive2] = 40;
		motorReq[rightdrive2] = 40;
		motorReq[rightdrive1] = 40;
		wait1Msec(500);

		motorReq[leftdrive1] = 0;
		motorReq[leftdrive2] = 0;
		motorReq[rightdrive2] = 0;
		motorReq[rightdrive1] = 0;

		SensorValue(driveencoder)=0;

		SensorValue(gyro)=0;
		wait1Msec(200);

		repeatUntil(SensorValue(linetrackleft) <=1800)
		{
			motorReq[leftdrive1] = -50;
			motorReq[leftdrive2] = -50;
			motorReq[rightdrive2] = -127;
			motorReq[rightdrive1] =-127;
		}
		motorReq[leftdrive1] = 0;
		motorReq[leftdrive2] = 0;
		motorReq[rightdrive2] = 0;
		motorReq[rightdrive1] = 0;

		repeatUntil(abs(SensorValue(driveencoder)) >= 300)
		{
			motorReq[leftdrive1] = -50;
			motorReq[leftdrive2]  = -50;
			motorReq[rightdrive1] = -127;
			motorReq[rightdrive2]  = -127;
		}
		motorReq[leftdrive1] = 10;
		motorReq[leftdrive2]  = 10;
		motorReq[rightdrive1] = 10;
		motorReq[rightdrive2]  = 10;

		wait1Msec(250);


		startTask(mobilepickup2);

		gyroturn(1500,100);

		gyroturn(1860,40);

		stopTask(mobilepickup2);
		startTask(mobileputdown1);

		movedistance(1300,127,2);

		startTask(mobilepickup);////////////////////////fourth cone pick up////////////////////////////

		wait1Msec(800);

		gyroturn(1900,40);

		movedistance(300,127,2);

		stopTask(mobilepickup);
		startTask(mobileputdown1);///////////////////////////fourth cone deposit//////////////////////////

		linetrack(2,63);

		wait1Msec(500);

		movedistance(100,-63,1);
		startTask(mobilepickup2);
		wait1Msec(250);


		motorReq[leftdrive1] = 35;
		motorReq[leftdrive2] = 35;
		motorReq[rightdrive2] = 35;
		motorReq[rightdrive1] = 35;
		wait1Msec(750);

		motorReq[leftdrive1] = 0;
		motorReq[leftdrive2] = 0;
		motorReq[rightdrive2] = 0;
		motorReq[rightdrive1] = 0;
		SensorValue(driveencoder)=0;

		SensorValue(gyro)=0;

		wait1Msec(200);

		movedistance(400,-127,2);

		linetrack(1,-127);

		movedistance(200,-127,1);

		wait1Msec(250);

		startTask(mobileputdown1);

		gyroturn(370,100);

		gyroturn(720,40);

		movedistance(575,127,2);

		startTask(mobilepickup);/////////////////////////fifth cone pickup////////////////////////

		wait1Msec(500);


		gyroturn(350,100);
		gyroturn(-20,40);


		linetrack(1,80);

		gyroturn(650,127);

		repeatUntil(SensorValue(sonicsensorright)>=2750)
		{
			motorReq[leftdrive1] = -127;
			motorReq[leftdrive2] = -127;
			motorReq[rightdrive2] = -127;
			motorReq[rightdrive1] = -127;
		}

		motorReq[leftdrive1] = 10;
		motorReq[leftdrive2] = 10;
		motorReq[rightdrive2] = 10;
		motorReq[rightdrive1] = 10;

		gyroturn(200,127);

		startTask(mobileputdown2);////////////////////////////////////fifth cone deposit////////////////////////

		movedistance(450,127,2);

		wait1Msec(250);

		movedistance(500,-127,1);

		displayNextLCDNumber(time1[T1]/10);

		break;

	}

}


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



task usercontrol()
{
	startTask(MotorSlewRateTask);
	motorSlew[leftdrive1] = 20;
	motorSlew[rightdrive1] = 20;
	motorSlew[leftdrive2] = 20;
	motorSlew[rightdrive1] = 20;

	stopTask(LCDControl);

	int speedval = 1;
	switch(auton)
	{
	default:///////////////////////////////////////////2 man normal drive/////////////////////////////

		while (true)
		{

			if (speedval==1)
			{
				motorReq[leftdrive1] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
				motorReq[leftdrive2] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
				motorReq[rightdrive2] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;
				motorReq[rightdrive1] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;
			}

			if (speedval==2)
			{
				motorReq[leftdrive1] = abs(vexRT[Ch3]) > 10 ? (vexRT[Ch3]/2) : 0;
				motorReq[leftdrive2] = abs(vexRT[Ch3]) > 10 ? (vexRT[Ch3]/2) : 0;
				motorReq[rightdrive2] = abs(vexRT[Ch2]) > 10 ? (vexRT[Ch2]/2) : 0;
				motorReq[rightdrive1] = abs(vexRT[Ch2]) > 10 ? (vexRT[Ch2]/2) : 0;
			}

			if (vexRT[Btn8UXmtr2]==1)
			{
				speedval = 1;
			}
			if (vexRT[Btn8DXmtr2]==1)
			{
				speedval = 2;
			}


			if (vexRT[Btn6U]==1)
			{
				stopTask(mobileputdown1);
				startTask(mobilepickup);
			}
			else if (vexRT[Btn6D]==1)
			{
				stopTask(mobilepickup);
				startTask(mobileputdown1);

			}

			if (vexRT[Btn5UXmtr2]==1)
			{
				motor[intake]=127;
			}
			else if (vexRT[Btn5DXmtr2]==1)
			{
				motor[intake]=-127;
			}
			else
			{
				motor[intake]=20;
			}

			if (vexRT[Btn7UXmtr2]==1)
			{
				motor[fourbarleft] = 127;
				motor[fourbarright] = 127;
			}
			else if (vexRT[Btn7DXmtr2]==1)
			{
				motor[fourbarleft] = -127;
				motor[fourbarright] = -127;
			}
			else
			{
				motor[fourbarleft] = 0;
				motor[fourbarright] = 0;
			}

			if (vexRT[Btn6UXmtr2]==1)
			{
				motor[conelift] = 127;
			}
			else if (vexRT[Btn6DXmtr2]==1)
			{
				motor[conelift] = -127;
			}
			else
			{
				motor[conelift] = 0;
			}

		}
		break;

	case -4:////////////////////////////skills 2 man with autoloader//////////////////////////////////////////

		SensorValue[liftencoder] = 0;
		SensorValue[mogoencoder] = 0;

		while (true)
		{

			motorReq[leftdrive1] = abs(vexRT[Ch3Xmtr2]) > 10 ? vexRT[Ch3Xmtr2] : 0;
			motorReq[leftdrive2] = abs(vexRT[Ch3Xmtr2]) > 10 ? vexRT[Ch3Xmtr2] : 0;
			motorReq[rightdrive2] = abs(vexRT[Ch2Xmtr2]) > 10 ? vexRT[Ch2Xmtr2] : 0;
			motorReq[rightdrive1] = abs(vexRT[Ch2Xmtr2]) > 10 ? vexRT[Ch2Xmtr2] : 0;


			if (vexRT[Btn6D]==1)
			{
				stopTask(mobilepickup);

				if (value==1)
				{
					startTask(mobileputdown2);
				}

				if (value==0)
				{
					startTask(mobileputdown1);
				}
			}

			if (vexRT[Btn6U]==1)
			{
				stopTask(mobileputdown1);
				stopTask(mobileputdown2);
				startTask(mobilepickup);
			}


			if (vexRT[Btn7UXmtr2]==1)
			{
				motor[fourbarleft] = 127;
				motor[fourbarright] = 127;
			}
			else if (vexRT[Btn7DXmtr2]==1)
			{
				motor[fourbarleft] = -127;
				motor[fourbarright] = -127;
			}
			else
			{
				motor[fourbarleft] = 0;
				motor[fourbarright] = 0;
			}


			if (vexRT[Btn5UXmtr2]==1)
			{
				motor[intake]=127;
			}

			else if (vexRT[Btn5DXmtr2]==1)
			{
				motor[intake]=-127;
			}
			else
			{
				motor[intake]=20;
			}

			if (vexRT[Btn6UXmtr2]==1)
			{
				motor[conelift]=127;
			}

			else if (vexRT[Btn6DXmtr2]==1)
			{
				motor[conelift]=-127;
			}
			else
			{
				motor[conelift]=0;
			}
		}
		break;

	case -5://////////////////////////////////alone///////////////////////

		SensorValue[liftencoder] = 0;
		SensorValue[mogoencoder] = 0;

		while (true)
		{

			motorReq[leftdrive1] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
			motorReq[leftdrive2] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
			motorReq[rightdrive2] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;
			motorReq[rightdrive1] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;


			if (vexRT[Btn7U]==1)
			{
				motor[fourbarleft] = 127;
				motor[fourbarright] = 127;
			}
			else if (vexRT[Btn7D]==1)
			{
				motor[fourbarleft] = -127;
				motor[fourbarright] = -127;
			}
			else
			{
				motor[fourbarleft] = 0;
				motor[fourbarright] = 0;
			}


			if (vexRT[Btn5U]==1)
			{
				motor[intake]=127;
			}

			else if (vexRT[Btn5D]==1)
			{
				motor[intake]=-127;
			}
			else
			{
				motor[intake]=20;
			}

			if (vexRT[Btn6U]==1)
			{
				motor[conelift]=127;
			}

			else if (vexRT[Btn6D]==1)
			{
				motor[conelift]=-127;
			}
			else
			{
				motor[conelift]=0;
			}

			if (vexRT[Btn8U]==1)
			{
				stopTask(mobileputdown1);
				startTask(mobilepickup);
			}
			else if (vexRT[Btn8D]==1)
			{
				stopTask(mobilepickup);
				startTask(mobileputdown1);
			}

		}
		break;

	case -6:////////////////////////////skills alone//////////////////////////////////////////

		SensorValue[liftencoder] = 0;
		SensorValue[mogoencoder] = 0;

		while (true)
		{

			motorReq[leftdrive1] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
			motorReq[leftdrive2] = abs(vexRT[Ch3]) > 10 ? vexRT[Ch3] : 0;
			motorReq[rightdrive2] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;
			motorReq[rightdrive1] = abs(vexRT[Ch2]) > 10 ? vexRT[Ch2] : 0;


			if (vexRT[Btn6D]==1)
			{
				stopTask(mobilepickup);

				if (value==1)
				{
					startTask(mobileputdown2);
				}

				if (value==0)
				{
					startTask(mobileputdown1);
				}
			}

			if (vexRT[Btn6U]==1)
			{
				stopTask(mobileputdown1);
				stopTask(mobileputdown2);
				startTask(mobilepickup);
			}

			if (vexRT[Btn5U]==1)
			{
				startTask(firstconelift);
			}

			if (vexRT[Btn5D]==1)
			{
				startTask(firstconedrop);
			}

		}
		break;

	}
}
