#pragma config(Sensor, in1,    potmobilelift,  sensorPotentiometer)
#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, in3,    linetrackright, sensorLineFollower)
#pragma config(Sensor, in4,    linetrackleft,  sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightencoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftencoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  liftencoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  sonicsensorleft, sensorSONAR_raw)
#pragma config(Sensor, dgtl11, sonicsensorright, sensorSONAR_raw)
#pragma config(Motor,  port1,           rightdrive1,   tmotorVex393HighSpeed_HBridge, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port2,           rightdrive2,   tmotorVex393HighSpeed_MC29, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port3,           fourbarleft,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           mobilelift,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           conelift,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           intake,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           fourbarright,  tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftdrive2,    tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, dgtl3)
#pragma config(Motor,  port10,          leftdrive1,    tmotorVex393HighSpeed_HBridge, openLoop, reversed, encoderPort, dgtl3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void gyroturn(int gyrovalue)
{
	wait1Msec(300);

	if(SensorValue(gyro)<gyrovalue)
	{

		repeatUntil(SensorValue(gyro)>= (gyrovalue*0.4))
		{
			motor[leftdrive1] = -127;
			motor[leftdrive2] = -127;
			motor[rightdrive2] = 127;
			motor[rightdrive1] = 127;
		}
		repeatUntil(SensorValue(gyro)>= (gyrovalue*0.6))
		{
			motor[leftdrive1] = -83;
			motor[leftdrive2] = -83;
			motor[rightdrive2] = 83;
			motor[rightdrive1] = 83;
		}
		repeatUntil(SensorValue(gyro)>= (gyrovalue))
		{
			motor[leftdrive1] = -40;
			motor[leftdrive2] = -40;
			motor[rightdrive2] = 40;
			motor[rightdrive1] = 40;
		}
		motor[leftdrive1] = 15;
		motor[leftdrive2] = 15;
		motor[rightdrive2] = -15;
		motor[rightdrive1] = -15;
	}


	else if(SensorValue(gyro)>gyrovalue)
	{

		repeatUntil(SensorValue(gyro)<= (gyrovalue*0.4))
		{
			motor[leftdrive1] = 127;
			motor[leftdrive2] = 127;
			motor[rightdrive2] = -127;
			motor[rightdrive1] = -127;
		}
		repeatUntil(SensorValue(gyro)>= (gyrovalue*0.6))
		{
			motor[leftdrive1] = 83;
			motor[leftdrive2] = 83;
			motor[rightdrive2] = -83;
			motor[rightdrive1] = -83;
		}
		repeatUntil(SensorValue(gyro)>= (gyrovalue))
		{
			motor[leftdrive1] = 40;
			motor[leftdrive2] = 40;
			motor[rightdrive2] = -40;
			motor[rightdrive1] = -40;
		}
		motor[leftdrive1] = -15;
		motor[leftdrive2] = -15;
		motor[rightdrive2] = 15;
		motor[rightdrive1] = 15;
	}

	wait1Msec(300);
}

void gyroturnmogo(int gyrovalue)
{
	wait1Msec(300);

	if(SensorValue(gyro)<gyrovalue)
	{

		repeatUntil(SensorValue(gyro)>= (gyrovalue*0.7))
		{
			motor[leftdrive1] = -127;
			motor[leftdrive2] = -127;
			motor[rightdrive2] = 127;
			motor[rightdrive1] = 127;
		}
		repeatUntil(SensorValue(gyro)>= (gyrovalue*0.9))
		{
			motor[leftdrive1] = -83;
			motor[leftdrive2] = -83;
			motor[rightdrive2] = 83;
			motor[rightdrive1] = 83;
		}
		repeatUntil(SensorValue(gyro)>= (gyrovalue))
		{
			motor[leftdrive1] = -40;
			motor[leftdrive2] = -40;
			motor[rightdrive2] = 40;
			motor[rightdrive1] = 40;
		}
		motor[leftdrive1] = 15;
		motor[leftdrive2] = 15;
		motor[rightdrive2] = -15;
		motor[rightdrive1] = -15;
	}


	else if(SensorValue(gyro)>gyrovalue)
	{

		repeatUntil(SensorValue(gyro)<= (gyrovalue*0.7))
		{
			motor[leftdrive1] = 127;
			motor[leftdrive2] = 127;
			motor[rightdrive2] = -127;
			motor[rightdrive1] = -127;
		}
		repeatUntil(SensorValue(gyro)>= (gyrovalue*0.9))
		{
			motor[leftdrive1] = 83;
			motor[leftdrive2] = 83;
			motor[rightdrive2] = -83;
			motor[rightdrive1] = -83;
		}
		repeatUntil(SensorValue(gyro)>= (gyrovalue))
		{
			motor[leftdrive1] = 40;
			motor[leftdrive2] = 40;
			motor[rightdrive2] = -40;
			motor[rightdrive1] = -40;
		}
		motor[leftdrive1] = -15;
		motor[leftdrive2] = -15;
		motor[rightdrive2] = 15;
		motor[rightdrive1] = 15;
	}

	wait1Msec(300);
}

task main()
{
SensorValue(gyro)=0;
gyroturn(900);
wait1Msec(10000);
gyroturnmogo(1800);
wait1Msec(1000);
}
