#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)
#pragma config(Motor,  port4,           chainbar,      tmotorVex393_MC29, openLoop, encoderPort, dgtl1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(0)
#pragma userControlDuration(60)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!


task chainbarControl()
{
float initialangle ;
float kP = 0.1;
float kI = 0.1;
float kD = 0.1;

float error;
float errorTotal;
float lasterror;
float proportion;
float integral;
float derivative;
float integralrange = 20;



while (true)

	{
		error = initialangle - SensorValue(potentiometer);
		if(error < integralrange && error != 0)
		{
			errorTotal+=error;
		}
		else
		{
			errorTotal = 0;
		}
		if (errorTotal > 50/kI)
		{
			errorTotal = 50/kI;
		}

		proportion = error * kP;
		integral = errorTotal * kI;
		derivative = (error - lasterror) * kD;

		lasterror = error;

		motor[port4] = proportion + integral + derivative;



		wait1Msec(50);



	}}


void pre_auton()
{}
task autonomous()
{}




task usercontrol()
{
	while (true)
	{
		if (vexRT[Btn7U]==1)
		{
			motor[port4] = 127;
			//initialangle
		}
		else if (vexRT[Btn7D]==1)
		{
			motor[port4]=-127;
		//	initialangle = SensorValue(I2C_5);
		}
		else
		{
			startTask (chainbarControl);
		}

	}
}
